language: java
language: node_js

node_js:
  - "6"

sudo: false

before_script:
  - npm install -g gulp
script: gulp test

jdk:
  - oraclejdk8

os:
  - linux
  
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8