package com.zfgc.mappers;

import com.zfgc.dbobj.AvatarGalleryDbObj;
import com.zfgc.dbobj.AvatarGalleryDbObjExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AvatarGalleryDbObjMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	int countByExample(AvatarGalleryDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	int deleteByExample(AvatarGalleryDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	int deleteByPrimaryKey(Integer avatarGalleryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	int insert(AvatarGalleryDbObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	int insertSelective(AvatarGalleryDbObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	List<AvatarGalleryDbObj> selectByExample(AvatarGalleryDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	AvatarGalleryDbObj selectByPrimaryKey(Integer avatarGalleryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	int updateByExampleSelective(@Param("record") AvatarGalleryDbObj record,
			@Param("example") AvatarGalleryDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	int updateByExample(@Param("record") AvatarGalleryDbObj record,
			@Param("example") AvatarGalleryDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	int updateByPrimaryKeySelective(AvatarGalleryDbObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AVATAR_GALLERY
	 * @mbggenerated  Mon Oct 22 22:59:46 EDT 2018
	 */
	int updateByPrimaryKey(AvatarGalleryDbObj record);
}