package com.zfgc.mappers;

import com.zfgc.dbobj.AvatarStagingDbObj;
import com.zfgc.dbobj.AvatarStagingDbObjExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AvatarStagingDbObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    long countByExample(AvatarStagingDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    int deleteByExample(AvatarStagingDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    int deleteByPrimaryKey(Integer avatarStagingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    int insert(AvatarStagingDbObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    int insertSelective(AvatarStagingDbObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    List<AvatarStagingDbObj> selectByExample(AvatarStagingDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    AvatarStagingDbObj selectByPrimaryKey(Integer avatarStagingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    int updateByExampleSelective(@Param("record") AvatarStagingDbObj record, @Param("example") AvatarStagingDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    int updateByExample(@Param("record") AvatarStagingDbObj record, @Param("example") AvatarStagingDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    int updateByPrimaryKeySelective(AvatarStagingDbObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVATAR_STAGING
     *
     * @mbg.generated Thu Oct 31 01:30:06 EDT 2019
     */
    int updateByPrimaryKey(AvatarStagingDbObj record);
}