package com.zfgc.mappers;

import com.zfgc.dbobj.BrBuddyIgnoreListDbObj;
import com.zfgc.dbobj.BrBuddyIgnoreListDbObjExample;
import com.zfgc.dbobj.BrBuddyIgnoreListDbObjKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrBuddyIgnoreListDbObjMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	long countByExample(BrBuddyIgnoreListDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	int deleteByExample(BrBuddyIgnoreListDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	int deleteByPrimaryKey(BrBuddyIgnoreListDbObjKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	int insert(BrBuddyIgnoreListDbObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	int insertSelective(BrBuddyIgnoreListDbObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	List<BrBuddyIgnoreListDbObj> selectByExample(BrBuddyIgnoreListDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	BrBuddyIgnoreListDbObj selectByPrimaryKey(BrBuddyIgnoreListDbObjKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	int updateByExampleSelective(@Param("record") BrBuddyIgnoreListDbObj record,
			@Param("example") BrBuddyIgnoreListDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	int updateByExample(@Param("record") BrBuddyIgnoreListDbObj record,
			@Param("example") BrBuddyIgnoreListDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	int updateByPrimaryKeySelective(BrBuddyIgnoreListDbObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_BUDDY_IGNORE_LIST
	 * @mbg.generated  Fri Jun 02 22:45:29 EDT 2017
	 */
	int updateByPrimaryKey(BrBuddyIgnoreListDbObj record);
}