package com.zfgc.mappers;

import com.zfgc.dbobj.BrMemberGroupNavTabDbObjExample;
import com.zfgc.dbobj.BrMemberGroupNavTabDbObjKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrMemberGroupNavTabDbObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_NAV_TAB
     *
     * @mbggenerated Thu Jan 26 21:57:27 EST 2017
     */
    int countByExample(BrMemberGroupNavTabDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_NAV_TAB
     *
     * @mbggenerated Thu Jan 26 21:57:27 EST 2017
     */
    int deleteByExample(BrMemberGroupNavTabDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_NAV_TAB
     *
     * @mbggenerated Thu Jan 26 21:57:27 EST 2017
     */
    int deleteByPrimaryKey(BrMemberGroupNavTabDbObjKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_NAV_TAB
     *
     * @mbggenerated Thu Jan 26 21:57:27 EST 2017
     */
    int insert(BrMemberGroupNavTabDbObjKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_NAV_TAB
     *
     * @mbggenerated Thu Jan 26 21:57:27 EST 2017
     */
    int insertSelective(BrMemberGroupNavTabDbObjKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_NAV_TAB
     *
     * @mbggenerated Thu Jan 26 21:57:27 EST 2017
     */
    List<BrMemberGroupNavTabDbObjKey> selectByExample(BrMemberGroupNavTabDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_NAV_TAB
     *
     * @mbggenerated Thu Jan 26 21:57:27 EST 2017
     */
    int updateByExampleSelective(@Param("record") BrMemberGroupNavTabDbObjKey record, @Param("example") BrMemberGroupNavTabDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_NAV_TAB
     *
     * @mbggenerated Thu Jan 26 21:57:27 EST 2017
     */
    int updateByExample(@Param("record") BrMemberGroupNavTabDbObjKey record, @Param("example") BrMemberGroupNavTabDbObjExample example);
}