package com.zfgc.mappers;

import com.zfgc.dbobj.brMemberGroupForumDbObj;
import com.zfgc.dbobj.brMemberGroupForumDbObjExample;
import com.zfgc.dbobj.brMemberGroupForumDbObjKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface brMemberGroupForumDbObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    int countByExample(brMemberGroupForumDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    int deleteByExample(brMemberGroupForumDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    int deleteByPrimaryKey(brMemberGroupForumDbObjKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    int insert(brMemberGroupForumDbObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    int insertSelective(brMemberGroupForumDbObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    List<brMemberGroupForumDbObj> selectByExample(brMemberGroupForumDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    brMemberGroupForumDbObj selectByPrimaryKey(brMemberGroupForumDbObjKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    int updateByExampleSelective(@Param("record") brMemberGroupForumDbObj record, @Param("example") brMemberGroupForumDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    int updateByExample(@Param("record") brMemberGroupForumDbObj record, @Param("example") brMemberGroupForumDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    int updateByPrimaryKeySelective(brMemberGroupForumDbObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BR_MEMBER_GROUP_FORUM
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    int updateByPrimaryKey(brMemberGroupForumDbObj record);
}