package com.zfgc.mappers;

import com.zfgc.dbobj.BrUserConversationDbObjExample;
import com.zfgc.dbobj.BrUserConversationDbObjKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.zfgc.dbobj.BrUserConversationDbObj;

public interface BrUserConversationDbObjMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	int countByExample(BrUserConversationDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	int deleteByExample(BrUserConversationDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	int deleteByPrimaryKey(BrUserConversationDbObjKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	int insert(BrUserConversationDbObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	int insertSelective(BrUserConversationDbObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	List<BrUserConversationDbObj> selectByExample(
			BrUserConversationDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	BrUserConversationDbObj selectByPrimaryKey(BrUserConversationDbObjKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	int updateByExampleSelective(
			@Param("record") BrUserConversationDbObj record,
			@Param("example") BrUserConversationDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	int updateByExample(@Param("record") BrUserConversationDbObj record,
			@Param("example") BrUserConversationDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	int updateByPrimaryKeySelective(BrUserConversationDbObj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BR_USER_CONVERSATION
	 * @mbggenerated  Sun Aug 19 21:53:20 EDT 2018
	 */
	int updateByPrimaryKey(BrUserConversationDbObj record);
}