package com.zfgc.mappers;

import com.zfgc.dbobj.ForumDbObj;
import com.zfgc.dbobj.ForumDbObjExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ForumDbObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    int countByExample(ForumDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    int deleteByExample(ForumDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    int deleteByPrimaryKey(Short forumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    int insert(ForumDbObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    int insertSelective(ForumDbObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    List<ForumDbObj> selectByExample(ForumDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    ForumDbObj selectByPrimaryKey(Short forumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    int updateByExampleSelective(@Param("record") ForumDbObj record, @Param("example") ForumDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    int updateByExample(@Param("record") ForumDbObj record, @Param("example") ForumDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    int updateByPrimaryKeySelective(ForumDbObj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORUM
     *
     * @mbggenerated Mon Dec 19 20:39:08 EST 2016
     */
    int updateByPrimaryKey(ForumDbObj record);
}