package com.zfgc.mappers;

import com.zfgc.dbobj.OutboxViewDbObj;
import com.zfgc.dbobj.OutboxViewDbObjExample;
import com.zfgc.dbobj.OutboxViewDbObjWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutboxViewDbObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOX_VIEW
     *
     * @mbggenerated Mon Sep 04 20:44:22 EDT 2017
     */
    int countByExample(OutboxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOX_VIEW
     *
     * @mbggenerated Mon Sep 04 20:44:22 EDT 2017
     */
    int deleteByExample(OutboxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOX_VIEW
     *
     * @mbggenerated Mon Sep 04 20:44:22 EDT 2017
     */
    int insert(OutboxViewDbObjWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOX_VIEW
     *
     * @mbggenerated Mon Sep 04 20:44:22 EDT 2017
     */
    int insertSelective(OutboxViewDbObjWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOX_VIEW
     *
     * @mbggenerated Mon Sep 04 20:44:22 EDT 2017
     */
    List<OutboxViewDbObjWithBLOBs> selectByExampleWithBLOBs(OutboxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOX_VIEW
     *
     * @mbggenerated Mon Sep 04 20:44:22 EDT 2017
     */
    List<OutboxViewDbObj> selectByExample(OutboxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOX_VIEW
     *
     * @mbggenerated Mon Sep 04 20:44:22 EDT 2017
     */
    int updateByExampleSelective(@Param("record") OutboxViewDbObjWithBLOBs record, @Param("example") OutboxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOX_VIEW
     *
     * @mbggenerated Mon Sep 04 20:44:22 EDT 2017
     */
    int updateByExampleWithBLOBs(@Param("record") OutboxViewDbObjWithBLOBs record, @Param("example") OutboxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOX_VIEW
     *
     * @mbggenerated Mon Sep 04 20:44:22 EDT 2017
     */
    int updateByExample(@Param("record") OutboxViewDbObj record, @Param("example") OutboxViewDbObjExample example);
}