package com.zfgc.mappers;

import com.zfgc.dbobj.PersonalMessageDbObj;
import com.zfgc.dbobj.PersonalMessageDbObjExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.zfgc.dbobj.PersonalMessageDbObjWithBLOBs;

public interface PersonalMessageDbObjMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	long countByExample(PersonalMessageDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	int deleteByExample(PersonalMessageDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	int deleteByPrimaryKey(Integer personalMessageId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	int insert(PersonalMessageDbObjWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	int insertSelective(PersonalMessageDbObjWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	List<PersonalMessageDbObjWithBLOBs> selectByExampleWithBLOBs(PersonalMessageDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	List<PersonalMessageDbObj> selectByExample(PersonalMessageDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	PersonalMessageDbObjWithBLOBs selectByPrimaryKey(Integer personalMessageId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	int updateByExampleSelective(@Param("record") PersonalMessageDbObjWithBLOBs record,
			@Param("example") PersonalMessageDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") PersonalMessageDbObjWithBLOBs record,
			@Param("example") PersonalMessageDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	int updateByExample(@Param("record") PersonalMessageDbObj record,
			@Param("example") PersonalMessageDbObjExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	int updateByPrimaryKeySelective(PersonalMessageDbObjWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	int updateByPrimaryKeyWithBLOBs(PersonalMessageDbObjWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSONAL_MESSAGE
	 * @mbg.generated  Sun Jul 21 13:17:53 EDT 2019
	 */
	int updateByPrimaryKey(PersonalMessageDbObj record);
}