package com.zfgc.mappers;

import com.zfgc.dbobj.PmArchiveBoxViewDbObj;
import com.zfgc.dbobj.PmArchiveBoxViewDbObjExample;
import com.zfgc.dbobj.PmArchiveBoxViewDbObjWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmArchiveBoxViewDbObjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ARCHIVE_BOX_VIEW
     *
     * @mbggenerated Tue Apr 24 22:48:54 EDT 2018
     */
    int countByExample(PmArchiveBoxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ARCHIVE_BOX_VIEW
     *
     * @mbggenerated Tue Apr 24 22:48:54 EDT 2018
     */
    int deleteByExample(PmArchiveBoxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ARCHIVE_BOX_VIEW
     *
     * @mbggenerated Tue Apr 24 22:48:54 EDT 2018
     */
    int insert(PmArchiveBoxViewDbObjWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ARCHIVE_BOX_VIEW
     *
     * @mbggenerated Tue Apr 24 22:48:54 EDT 2018
     */
    int insertSelective(PmArchiveBoxViewDbObjWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ARCHIVE_BOX_VIEW
     *
     * @mbggenerated Tue Apr 24 22:48:54 EDT 2018
     */
    List<PmArchiveBoxViewDbObjWithBLOBs> selectByExampleWithBLOBs(PmArchiveBoxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ARCHIVE_BOX_VIEW
     *
     * @mbggenerated Tue Apr 24 22:48:54 EDT 2018
     */
    List<PmArchiveBoxViewDbObj> selectByExample(PmArchiveBoxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ARCHIVE_BOX_VIEW
     *
     * @mbggenerated Tue Apr 24 22:48:54 EDT 2018
     */
    int updateByExampleSelective(@Param("record") PmArchiveBoxViewDbObjWithBLOBs record, @Param("example") PmArchiveBoxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ARCHIVE_BOX_VIEW
     *
     * @mbggenerated Tue Apr 24 22:48:54 EDT 2018
     */
    int updateByExampleWithBLOBs(@Param("record") PmArchiveBoxViewDbObjWithBLOBs record, @Param("example") PmArchiveBoxViewDbObjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PM_ARCHIVE_BOX_VIEW
     *
     * @mbggenerated Tue Apr 24 22:48:54 EDT 2018
     */
    int updateByExample(@Param("record") PmArchiveBoxViewDbObj record, @Param("example") PmArchiveBoxViewDbObjExample example);
}