CREATE TABLE IF NOT EXISTS `BB_CODE_ATTRIBUTE` (
  `BB_CODE_ATTRIBUTE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATTRIBUTE_DATA_TYPE` int(11) NOT NULL,
  `ATTRIBUTE_INDEX` tinyint(4) NOT NULL,
  `BB_CODE_ATTRIBUTE_MODE_ID` tinyint(4) NOT NULL,
  `NAME` varchar(32) NOT NULL,
  PRIMARY KEY (`BB_CODE_ATTRIBUTE_ID`),
  KEY `FK_BBCODE_ATTRIBUTE_ATTRIBUTE_DATA_TYPE` (`ATTRIBUTE_DATA_TYPE`),
  CONSTRAINT `FK_BBCODE_ATTRIBUTE_ATTRIBUTE_DATA_TYPE` FOREIGN KEY (`ATTRIBUTE_DATA_TYPE`) REFERENCES `ATTRIBUTE_DATA_TYPE` (`ATTRIBUTE_DATA_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;