CREATE TABLE `BR_BUDDY_IGNORE_LIST` (
	`USER_A_ID` INT(11) NOT NULL,
	`USER_B_ID` INT(11) NOT NULL,
	`BUDDY_FLAG` BIT(1) NOT NULL,
	`IGNORE_FLAG` BIT(1) NOT NULL,
	PRIMARY KEY (`USER_A_ID`, `USER_B_ID`),
	INDEX `FK_USER_B_ID_USERS` (`USER_B_ID`),
	CONSTRAINT `FK_USER_A_ID_USERS` FOREIGN KEY (`USER_A_ID`) REFERENCES `users` (`USERS_ID`),
	CONSTRAINT `FK_USER_B_ID_USERS` FOREIGN KEY (`USER_B_ID`) REFERENCES `users` (`USERS_ID`)
)
ENGINE=InnoDB
;
