CREATE TABLE IF NOT EXISTS `BR_CONVERSATION_USER` (
  `CONVERSATION_ID` int(11) NOT NULL,
  `USERS_ID` int(11) NOT NULL,
  PRIMARY KEY (`CONVERSATION_ID`,`USERS_ID`),
  KEY `FK_CONVERSATION_USER_USERS_ID` (`USERS_ID`),
  CONSTRAINT `FK_CONVERSATION_USER_CONVERSATION_ID` FOREIGN KEY (`CONVERSATION_ID`) REFERENCES `PM_CONVERSATION` (`PM_CONVERSATION_ID`),
  CONSTRAINT `FK_CONVERSATION_USER_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;