CREATE TABLE `BR_FORUM_PERMISSIONS` (
	`BR_THREAD_PERMISSIONS_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`FORUM_ID` SMALLINT(5) UNSIGNED NOT NULL,
	`PERMISSIONS_ID` INT(11) NOT NULL,
	`READ_ONLY_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (`BR_THREAD_PERMISSIONS_ID`),
	INDEX `BR_FORUM_PERMISSIONS_FORUM_FORUM_ID` (`FORUM_ID`),
	INDEX `BR_FORUM_PERMISSIONS_PERMISSION_PERMISSIONS_ID` (`PERMISSIONS_ID`),
	CONSTRAINT `BR_FORUM_PERMISSIONS_FORUM_FORUM_ID` FOREIGN KEY (`FORUM_ID`) REFERENCES `FORUM` (`FORUM_ID`),
	CONSTRAINT `BR_FORUM_PERMISSIONS_PERMISSION_PERMISSIONS_ID` FOREIGN KEY (`PERMISSIONS_ID`) REFERENCES `PERMISSIONS` (`PERMISSIONS_ID`)
)
ENGINE=InnoDB
;
