CREATE TABLE `BR_MEMBER_GROUP_FORUM` (
	`FORUM_ID` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`PERMISSION_ID` INT(11) NOT NULL DEFAULT '0',
	`READ_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`WRITE_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (`FORUM_ID`, `PERMISSION_ID`),
	INDEX `FK_BR_MEMBER_GROUP_FORUM_PERMISSION_ID` (`PERMISSION_ID`),
	CONSTRAINT `FK_BR_MEMBER_GROUP_FORUM_PERMISSION_ID` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `PERMISSIONS` (`PERMISSIONS_ID`),
	CONSTRAINT `FK_BR_MEMBER_GROUP_FORUM_FORUM` FOREIGN KEY (`FORUM_ID`) REFERENCES `FORUM` (`FORUM_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
