CREATE TABLE `BR_PM_CONVERSATION_ARCHIVE` (
	`PM_CONVERSATION_ID` INT(11) NOT NULL,
	`USERS_ID` INT(11) NOT NULL,
	`ARCHIVE_DT` DATETIME NOT NULL,
	INDEX `FK_BR_PM_CONVERSATION_ARCHIVE_PM_CONVERSATION_ID` (`PM_CONVERSATION_ID`),
	INDEX `FK_BR_PM_CONVERSATION_ARCHIVE_USERS_ID` (`USERS_ID`),
	PRIMARY KEY (`PM_CONVERSATION_ID`, `USERS_ID`),
	CONSTRAINT `FK_BR_PM_CONVERSATION_ARCHIVE_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`),
	CONSTRAINT `FK_BR_PM_CONVERSATION_ARCHIVE_PM_CONVERSATION_ID` FOREIGN KEY (`PM_CONVERSATION_ID`) REFERENCES `PM_CONVERSATION` (`PM_CONVERSATION_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
