-- --------------------------------------------------------
-- Host:                         zfgc.com
-- Server version:               5.5.60-0ubuntu0.14.04.1 - (Ubuntu)
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table zfgc3_dev.BR_PM_CONVERSATION_USER_INVITE
CREATE TABLE IF NOT EXISTS `BR_PM_CONVERSATION_USER_INVITE` (
  `PM_CONVERSATION_ID` int(11) NOT NULL,
  `USERS_ID` int(11) NOT NULL,
  `INVITE_CODE` char(50) NOT NULL,
  `DECRYPTOR` varchar(3000) NOT NULL,
  `INVITER_ID` int(11) NOT NULL,
  PRIMARY KEY (`PM_CONVERSATION_ID`,`USERS_ID`),
  KEY `FK_BR_PM_CONVERSATION_USER_INVITE_USER_ID` (`USERS_ID`),
  KEY `FK_BR_PM_CONVERSATION_USER_INVITE_INVITER_ID` (`INVITER_ID`),
  CONSTRAINT `FK_BR_PM_CONVERSATION_USER_INVITE_INVITER_ID` FOREIGN KEY (`INVITER_ID`) REFERENCES `users` (`USERS_ID`),
  CONSTRAINT `FK_BR_PM_CONVERSATION_USER_INVITE_USER_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`),
  CONSTRAINT `FK_PM_CONVERSATION_ID` FOREIGN KEY (`PM_CONVERSATION_ID`) REFERENCES `PM_CONVERSATION` (`PM_CONVERSATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
