CREATE TABLE `BR_USERS_HOSTNAME` (
	`USERS_ID` INT(11) NOT NULL,
	`HOSTNAME_ID` INT(11) NOT NULL,
	PRIMARY KEY (`USERS_ID`, `HOSTNAME_ID`),
	INDEX `BR_USERS_HOSTNAME_HOSTNAME_ID` (`HOSTNAME_ID`),
	CONSTRAINT `BR_USERS_HOSTNAME_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`),
	CONSTRAINT `BR_USERS_HOSTNAME_HOSTNAME_ID` FOREIGN KEY (`HOSTNAME_ID`) REFERENCES `HOSTNAME` (`HOSTNAME_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
