CREATE TABLE `BR_USER_THREAD_SUBSCRIPTION` (
	`USERS_ID` INT(11) NOT NULL,
	`THREAD_ID` INT(11) NOT NULL,
	`RECEIVE_PM_FLAG` BIT(1) NOT NULL,
	`RECEIVE_EMAIL_FLAG` BIT(1) NOT NULL,
	PRIMARY KEY (`USERS_ID`, `THREAD_ID`),
	INDEX `FK_USERS_THREAD_SUB_THREAD_ID` (`THREAD_ID`),
	CONSTRAINT `FK_USERS_THREAD_SUB_THREAD_ID` FOREIGN KEY (`THREAD_ID`) REFERENCES `THREAD` (`THREAD_ID`),
	CONSTRAINT `FK_USERS_THREAD_SUB_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
)
ENGINE=InnoDB
;
