-- --------------------------------------------------------
-- Host:                         zfgc.com
-- Server version:               5.5.60-0ubuntu0.14.04.1 - (Ubuntu)
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table zfgc3_dev.BR_USER_CONVERSATION
CREATE TABLE IF NOT EXISTS `BR_USER_CONVERSATION` (
  `USERS_ID` int(11) NOT NULL,
  `PM_CONVERSATION_ID` int(11) NOT NULL,
  `READ_FLAG` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`USERS_ID`,`PM_CONVERSATION_ID`),
  KEY `USER_CONVERSATION_PM_CONVERSATION_ID` (`PM_CONVERSATION_ID`),
  CONSTRAINT `USER_CONVERSATION_PM_CONVERSATION_ID` FOREIGN KEY (`PM_CONVERSATION_ID`) REFERENCES `PM_CONVERSATION` (`PM_CONVERSATION_ID`),
  CONSTRAINT `USER_CONVERSATION_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
