SELECT F.FORUM_ID,
	   MGF.PERMISSION_ID,
	   MGF.READ_FLAG,
	   MGF.WRITE_FLAG,
	   F.NAME,
	   F.DESCRIPTION,
	   F.CATEGORY_ID,
	   F.PARENT_FORUM_ID
FROM FORUM F
JOIN BR_MEMBER_GROUP_FORUM MGF ON MGF.FORUM_ID = F.FORUM_ID
WHERE MGF.READ_FLAG = TRUE OR MGF.WRITE_FLAG = TRUE