CREATE OR REPLACE VIEW MEMBER_LISTING_VIEW AS
SELECT U.USERS_ID, U.DISPLAY_NAME, U.EMAIL_ADDRESS, U.LAST_LOGIN, U.DATE_REGISTERED, LKGS.GROUP_NAME, T.LKUP_TIMEZONES_ID, T.TIME_ZONE
FROM users U
JOIN LKUP_MEMBER_GROUP LKGP ON LKGP.MEMBER_GROUP_ID = U.PRIMARY_MEMBER_GROUP_ID
JOIN BR_MEMBER_GROUP_USER GS ON GS.USERS_ID = U.USERS_ID
JOIN LKUP_MEMBER_GROUP LKGS ON LKGS.MEMBER_GROUP_ID = GS.MEMBER_GROUP_ID
JOIN LKUP_TIMEZONES T ON T.LKUP_TIMEZONES_ID = U.TIME_OFFSET
WHERE U.ACTIVE_FLAG = 1
ORDER BY U.DISPLAY_NAME ASC