CREATE OR REPLACE VIEW MEMBER_LISTING_VIEW AS
SELECT U.USERS_ID, U.DISPLAY_NAME, E.EMAIL_ADDRESS, U.LAST_LOGIN, U.DATE_REGISTERED, LKGS.GROUP_NAME, T.LKUP_TIMEZONES_ID, T.TIME_ZONE, U.ACTIVE_FLAG, IP.IP_ADDRESS
FROM users U
JOIN LKUP_MEMBER_GROUP LKGP ON LKGP.MEMBER_GROUP_ID = U.PRIMARY_MEMBER_GROUP_ID
JOIN LKUP_MEMBER_GROUP LKGS ON LKGS.MEMBER_GROUP_ID = LKGP.MEMBER_GROUP_ID
JOIN LKUP_TIMEZONES T ON T.LKUP_TIMEZONES_ID = U.TIME_OFFSET
LEFT JOIN USER_CONTACT_SETTINGS C ON C.USERS_ID = U.USERS_ID
LEFT JOIN EMAIL_ADDRESS E ON E.EMAIL_ADDRESS_ID = C.EMAIL_ADDRESS_ID
LEFT JOIN IP_ADDRESS IP ON U.PRIMARY_IP = IP.IP_ADDRESS_ID
ORDER BY U.DISPLAY_NAME ASC