SELECT PARENT.NAV_TAB_ID, 
       PARENT.TITLE, 
       PARENT.SEQUENCE_NO, 
       CHILD.NAV_TAB_ID AS CHILD_NAV_TAB_ID, 
       CHILD.PARENT_TAB_ID, 
       CHILD.TITLE AS CHILD_TITLE, 
       CHILD.SEQUENCE_NO AS CHILD_SEQUENCE_NO,
       CHILD.SECTION_CODE
FROM NAV_TAB PARENT
INNER JOIN NAV_TAB CHILD ON PARENT.NAV_TAB_ID = CHILD.PARENT_TAB_ID
ORDER BY PARENT.SEQUENCE_NO ASC, CHILD_SEQUENCE_NO ASC