select `PARENT`.`NAV_TAB_ID` AS `NAV_TAB_ID`,
	   `PARENT`.`TITLE` AS `TITLE`,
	   `PARENT`.`SEQUENCE_NO` AS `SEQUENCE_NO`,
	   PARENT.FA_ICON,
	   `CHILD`.`NAV_TAB_ID` AS `CHILD_NAV_TAB_ID`,
	   `CHILD`.`PARENT_TAB_ID` AS `PARENT_TAB_ID`,
	   `CHILD`.`TITLE` AS `CHILD_TITLE`,
	   `CHILD`.`SEQUENCE_NO` AS `CHILD_SEQUENCE_NO`,
	   `CHILD`.`LKUP_NAV_SECTION_ID` AS `LKUP_NAV_SECTION_ID`,
	   `CHILD`.`ALLOW_SELF_FLAG` AS `ALLOW_SELF_FLAG` 
from (`NAV_TAB` `PARENT` 
join `NAV_TAB` `CHILD` on((`PARENT`.`NAV_TAB_ID` = `CHILD`.`PARENT_TAB_ID`))) 
order by `PARENT`.`SEQUENCE_NO`,`CHILD`.`SEQUENCE_NO`