SELECT C.PM_CONVERSATION_ID, P.PERSONAL_MESSAGE_ID, P.SENDER_ID, P.RECEIVER_ID, P.SENT_DT, P.SUBJECT, P.MESSAGE, P.SEND_COPY_FLAG, P.READ_FLAG
FROM PM_CONVERSATION C
JOIN BR_PM_CONVERSATION_ARCHIVE A ON C.PM_CONVERSATION_ID = A.PM_CONVERSATION_ID
JOIN PERSONAL_MESSAGE P ON P.PM_CONVERSATION_ID = C.PM_CONVERSATION_ID
WHERE P.SENT_DT = (SELECT MAX(P2.SENT_DT) FROM PERSONAL_MESSAGE P2 WHERE P2.PM_CONVERSATION_ID = P.PM_CONVERSATION_ID AND P2.SENT_DT <= A.ARCHIVE_DT)