select C.PM_CONVERSATION_ID,
       PM.SENDER_ID,
		 US.DISPLAY_NAME AS SENDER_NAME,
		 C.INITIATOR_ID,
		 UI.DISPLAY_NAME AS INITIATOR_NAME,
		 BRU.USERS_ID AS RECEIVER_ID,
		 PM.PERSONAL_MESSAGE_ID AS PERSONAL_MESSAGE_ID,
		 C.SUBJECT AS SUBJECT,
		 PM.MESSAGE AS MESSAGE,
		 PM.SENT_DT AS SENT_DT,
		 C.START_DT AS START_DT,
		 BRU.READ_FLAG
 from PM_CONVERSATION C
 join PERSONAL_MESSAGE PM on PM.PM_CONVERSATION_ID = C.PM_CONVERSATION_ID
 join users UI on UI.USERS_ID = C.INITIATOR_ID 
 join users US on US.USERS_ID = PM.SENDER_ID
 join BR_USER_CONVERSATION BRU on BRU.PM_CONVERSATION_ID = C.PM_CONVERSATION_ID
 left join BR_PM_CONVERSATION_ARCHIVE A on A.USERS_ID = PM.RECEIVER_ID and A.PM_CONVERSATION_ID = C.PM_CONVERSATION_ID
 where ((PM.SENT_DT = (select max(PM2.SENT_DT) from PERSONAL_MESSAGE PM2 where (PM2.PM_CONVERSATION_ID = C.PM_CONVERSATION_ID))) and isnull(A.USERS_ID))