SELECT T.THREAD_ID,
       T.NAME,
       T.THREAD_STARTER_ID,
       U.DISPLAY_NAME AS THREAD_STARTER_NAME
FROM THREAD T
JOIN BR_USER_THREAD_SUBSCRIPTION S ON T.THREAD_ID = S.THREAD_ID
JOIN users U ON T.THREAD_STARTER_ID = U.USERS_ID