SELECT T.THREAD_ID,
       T.NAME,
       S.USERS_ID AS SUBSCRIBER_ID,
       U2.DISPLAY_NAME AS SUBSCRIBER_NAME,
       T.THREAD_STARTER_ID,
       U.DISPLAY_NAME AS THREAD_STARTER_NAME
FROM THREAD T
JOIN BR_USER_THREAD_SUBSCRIPTION S ON T.THREAD_ID = S.THREAD_ID
JOIN users U ON T.THREAD_STARTER_ID = U.USERS_ID
JOIN users U2 ON S.USERS_ID = U2.USERS_ID