CREATE OR REPLACE VIEW UPCOMING_CALENDAR_VIEW AS
SELECT CALENDAR_EVENT_ID AS EVENT_ID, EVENT_NAME, DATE(EVENT_DT) AS EVENT_DT, 0 AS BIRTHDATE_FLAG
FROM CALENDAR_EVENT

UNION

SELECT USERS_ID AS EVENT_ID, DISPLAY_NAME AS EVENT_NAME, DATE(BIRTH_DATE) AS EVENT_DT, 1 AS BIRTHDATE_FLAG
FROM users