SELECT
U.USERS_ID,
U.DISPLAY_NAME,
A.PARAM AS FORUM_ID,
F.NAME AS FORUM_NAME
FROM users U
JOIN USER_CONNECTION C ON C.USERS_ID = U.USERS_ID
JOIN USER_CURRENT_ACTION A ON A.USER_CURRENT_ACTION_ID = C.USER_ACTION_ID
JOIN FORUM F ON F.FORUM_ID = A.PARAM
WHERE A.LOCATION_ID = 2