SELECT
U.USERS_ID,
U.DISPLAY_NAME
FROM users U
JOIN USER_CONNECTION C ON C.USERS_ID = U.USERS_ID
JOIN USER_CURRENT_ACTION A ON A.USER_CURRENT_ACTION_ID = C.USER_ACTION_ID
WHERE A.USER_CURRENT_ACTION_ID = 2