SELECT U.USERS_ID,
	   CASE
	      WHEN PP.PERMISSIONS_CODE IS NOT NULL THEN PP.PERMISSIONS_CODE
	      ELSE SP.PERMISSIONS_CODE
	   END AS PERMISSIONS_CODE
FROM users U
JOIN LKUP_MEMBER_GROUP PG ON PG.MEMBER_GROUP_ID = U.PRIMARY_MEMBER_GROUP_ID
JOIN BR_PERMISSIONS_MEMBER_GROUP PMG ON PMG.MEMBER_GROUP_ID = PG.MEMBER_GROUP_ID
JOIN PERMISSIONS PP ON PP.PERMISSIONS_ID = PMG.PERMISSIONS_ID
LEFT JOIN BR_MEMBER_GROUP_USER SMG ON SMG.USERS_ID = U.USERS_ID
LEFT JOIN BR_PERMISSIONS_MEMBER_GROUP SMG2 ON SMG2.MEMBER_GROUP_ID = SMG.MEMBER_GROUP_ID
LEFT JOIN PERMISSIONS SP ON SP.PERMISSIONS_ID = SMG2.PERMISSIONS_ID