SELECT U.USERS_ID,
       U2.LOGIN_NAME,
       U2.DISPLAY_NAME,
       E.EMAIL_ADDRESS_ID,
       E.EMAIL_ADDRESS,
       U2.ACTIVE_FLAG
FROM USER_CONTACT_SETTINGS U
JOIN users U2 ON U2.USERS_ID = U.USERS_ID 
JOIN EMAIL_ADDRESS E ON E.EMAIL_ADDRESS_ID = U.EMAIL_ADDRESS_ID