SELECT U.USERS_ID, U.DISPLAY_NAME, I.IP_ADDRESS, C.AGENT_TYPE, C.AGENT_NAME, C.AGENT_VERSION, C.OS_TYPE, C.OS_NAME, C.SESSION_ID
FROM users U
JOIN USER_CONNECTION C ON C.USERS_ID = U.USERS_ID
JOIN IP_ADDRESS I ON I.IP_ADDRESS_ID = C.IP_ADDRESS_ID