CREATE TABLE IF NOT EXISTS `ATTRIBUTE_DATA_TYPE` (
  `ATTRIBUTE_DATA_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE_NAME` varchar(12) NOT NULL,
  PRIMARY KEY (`ATTRIBUTE_DATA_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;