CREATE TABLE IF NOT EXISTS `BB_CODE_CONFIG` (
  `BB_CODE_CONFIG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(16) NOT NULL,
  `END_TAG` varchar(512) NOT NULL,
  `PROCESS_CONTENT_FLAG` bit(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`BB_CODE_CONFIG_ID`),
  UNIQUE KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- Dumping data for table zfgc3_dev.BB_CODE_CONFIG: ~5 rows (approximately)
/*!40000 ALTER TABLE `BB_CODE_CONFIG` DISABLE KEYS */;
INSERT INTO `BB_CODE_CONFIG` (`BB_CODE_CONFIG_ID`, `CODE`, `END_TAG`, `PROCESS_CONTENT_FLAG`) VALUES
	(1, 'b', '</span>', b'1'),
	(2, 'i', '</span>', b'1'),
	(3, 'u', '</span>', b'1'),
	(4, 'url', '</a>', b'0'),
	(5, 'img', '</span>', b'0');
/*!40000 ALTER TABLE `BB_CODE_CONFIG` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;