CREATE TABLE IF NOT EXISTS `BR_USER_CONVERSATION` (
  `USERS_ID` int(11) NOT NULL,
  `PM_CONVERSATION_ID` int(11) NOT NULL,
  PRIMARY KEY (`USERS_ID`,`PM_CONVERSATION_ID`),
  KEY `USER_CONVERSATION_PM_CONVERSATION_ID` (`PM_CONVERSATION_ID`),
  CONSTRAINT `USER_CONVERSATION_PM_CONVERSATION_ID` FOREIGN KEY (`PM_CONVERSATION_ID`) REFERENCES `PM_CONVERSATION` (`PM_CONVERSATION_ID`),
  CONSTRAINT `USER_CONVERSATION_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
