CREATE TABLE `CALENDAR_EVENT` (
	`CALENDAR_EVENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`EVERY_YEAR_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`EVENT_NAME` VARCHAR(50) NOT NULL,
	`EVENT_DT` DATE NOT NULL,
	PRIMARY KEY (`CALENDAR_EVENT_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;