CREATE TABLE `EMAIL_ADDRESS` (
	`EMAIL_ADDRESS` VARCHAR(254) NOT NULL,
	`IS_SPAMMER_FLAG` BIT(1) NOT NULL DEFAULT b'1',
	`EMAIL_ADDRESS_ID` INT(11) NOT NULL,
	PRIMARY KEY (`EMAIL_ADDRESS_ID`),
	UNIQUE INDEX `EMAIL_ADDRESS` (`EMAIL_ADDRESS`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB