CREATE TABLE `IP_ADDRESS` (
	`IP_ADDRESS_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`IP_ADDRESS` VARCHAR(39) NOT NULL DEFAULT '0.0.0.0',
	`VERSION` TINYINT(4) NOT NULL DEFAULT '4',
	`IS_SPAMMER_FLAG` BIT(1) NOT NULL DEFAULT b'1',
	`IS_LOCKED_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`LOCKED_UNTIL` DATETIME NULL DEFAULT NULL,
	`LOGIN_ATTEMPTS` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`IP_ADDRESS_ID`),
	UNIQUE INDEX `IP_ADDRESS` (`IP_ADDRESS`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
