CREATE TABLE `NAV_TAB` (
	`NAV_TAB_ID` INT(11) NOT NULL,
	`PARENT_TAB_ID` INT(11) NULL DEFAULT NULL,
	`TITLE` VARCHAR(32) NOT NULL,
	`SEQUENCE_NO` INT(11) NOT NULL DEFAULT '0',
	`SECTION_CODE` CHAR(4) NULL DEFAULT NULL,
	PRIMARY KEY (`NAV_TAB_ID`),
	UNIQUE INDEX `SECTION_CODE` (`SECTION_CODE`),
	INDEX `FK_NAV_TAB_ID_PARENT_TAB_ID` (`PARENT_TAB_ID`),
	CONSTRAINT `FK_NAV_TAB_ID_PARENT_TAB_ID` FOREIGN KEY (`PARENT_TAB_ID`) REFERENCES `NAV_TAB` (`NAV_TAB_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

INSERT INTO `NAV_TAB` (`NAV_TAB_ID`, `PARENT_TAB_ID`, `TITLE`, `SEQUENCE_NO`, `SECTION_CODE`) VALUES
	(0, NULL, 'Profile Info', -4, 'PLIN'),
	(1, NULL, 'Modify Profile', -3, 'MDPL'),
	(2, NULL, 'Messaging', -2, 'MSGS'),
	(3, NULL, 'Track User', -1, 'TRUS'),
	(4, 0, 'Summary', 1, 'SUMM'),
	(5, 1, 'Account Settings', 1, 'ACTS'),
	(6, 1, 'Forum Profile', 1, 'FMPL');
