CREATE TABLE `NAV_TAB` (
	`NAV_TAB_ID` INT(11) NOT NULL,
	`LKUP_NAV_SECTION_ID` INT(11) NOT NULL,
	`PARENT_TAB_ID` INT(11) NULL DEFAULT NULL,
	`TITLE` VARCHAR(32) NOT NULL,
	`SEQUENCE_NO` INT(11) NOT NULL DEFAULT '0',
	`ALLOW_SELF_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`FA_ICON` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`NAV_TAB_ID`),
	INDEX `FK_NAV_TAB_ID_PARENT_TAB_ID` (`PARENT_TAB_ID`),
	INDEX `FK_LKUP_NAV_SECTION_ID_NAV_TAB` (`LKUP_NAV_SECTION_ID`),
	CONSTRAINT `FK_LKUP_NAV_SECTION_ID_NAV_TAB` FOREIGN KEY (`LKUP_NAV_SECTION_ID`) REFERENCES `LKUP_NAV_SECTIONS` (`LKUP_NAV_SECTIONS_ID`),
	CONSTRAINT `FK_NAV_TAB_ID_PARENT_TAB_ID` FOREIGN KEY (`PARENT_TAB_ID`) REFERENCES `NAV_TAB` (`NAV_TAB_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
