CREATE TABLE `NOTIFICATION_SETTINGS` (
	`NOTIFICATION_SETTINGS_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USERS_ID` INT(11) NOT NULL,
	`AUTO_SUBSCRIBE_FLAG` BIT(1) NOT NULL,
	`SEND_POST_IN_EMAIL_FLAG` BIT(1) NOT NULL,
	`INSTANT_FLAG` BIT(1) NOT NULL,
	`FREQUENCY_ID` INT(11) NOT NULL DEFAULT '0',
	`ONLY_FIRST_FLAG` BIT(1) NOT NULL,
	`REPLIES_FLAG` BIT(1) NOT NULL,
	`MODERATION_FLAG` BIT(1) NOT NULL,
	`ONLY_ME_FLAG` BIT(1) NOT NULL,
	`KARMA_EMAIL_FLAG` BIT(1) NOT NULL,
	`KARMA_PM_FLAG` BIT(1) NOT NULL,
	`TAGGED_EMAIL_FLAG` BIT(1) NOT NULL,
	`TAGGED_PM_FLAG` BIT(1) NOT NULL,
	`PM_EMAIL_FLAG` BIT(1) NOT NULL,
	`POSTED_IN_FLAG` BIT(1) NOT NULL,
	`REPLIES_TO_ME_FLAG` BIT(1) NOT NULL,
	PRIMARY KEY (`NOTIFICATION_SETTINGS_ID`),
	UNIQUE INDEX `USERS_ID` (`USERS_ID`),
	INDEX `FK_NOTIFICATION_SETTINGS_FREQUENCY_ID` (`FREQUENCY_ID`),
	CONSTRAINT `FK_NOTIFICATION_SETTINGS_FREQUENCY_ID` FOREIGN KEY (`FREQUENCY_ID`) REFERENCES `LKUP_NOTIFICATION_FREQUENCY` (`NOTIFICATION_FREQUENCY_ID`),
	CONSTRAINT `FK_NOTIFICATION_SETTINGS_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
