CREATE TABLE `NOTIFICATION_SETTINGS` (
	`NOTIFICATION_SETTINGS_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USERS_ID` INT(11) NOT NULL,
	`AUTO_SUBSCRIBE_FLAG` BIT(1) NOT NULL,
	`SEND_POST_IN_EMAIL_FLAG` BIT(1) NOT NULL,
	`INSANT_FLAG` BIT(1) NOT NULL,
	`DAILY_FLAG` BIT(1) NOT NULL,
	`WEEKLY_FLAG` BIT(1) NOT NULL,
	`ONLY_FIRST_FLAG` BIT(1) NOT NULL,
	`REPLIES_FLAG` BIT(1) NOT NULL,
	`MODERATION_FLAG` BIT(1) NOT NULL,
	`ONLY_ME_FLAG` BIT(1) NOT NULL,
	`KARMA_EMAIL_FLAG` BIT(1) NOT NULL,
	`KARMA_PM_FLAG` BIT(1) NOT NULL,
	`TAGGED_EMAIL_FLAG` BIT(1) NOT NULL,
	`TAGGED_PM_FLAG` BIT(1) NOT NULL,
	`PM_EMAIL_FLAG` BIT(1) NOT NULL,
	PRIMARY KEY (`NOTIFICATION_SETTINGS_ID`),
	UNIQUE INDEX `USERS_ID` (`USERS_ID`),
	CONSTRAINT `FK_NOTIFICATION_SETTINGS_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
)
ENGINE=InnoDB
;
