CREATE TABLE `PERSONAL_MESSAGING_SETTINGS` (
	`PERSONAL_MESSAGING_SETTINGS_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USERS_ID` INT(11) NOT NULL,
	`DISPLAY_SETTING_ID` INT(11) NOT NULL,
	`RECENT_AT_TOP_FLAG` BIT(1) NOT NULL,
	`RECEIVE_FROM_ID` INT(11) NOT NULL,
	`NOTIFY_FREQUENCY_ID` INT(11) NOT NULL,
	`SAVE_TO_SENT_FLAG` BIT(1) NOT NULL,
	PRIMARY KEY (`PERSONAL_MESSAGING_SETTINGS_ID`),
	UNIQUE INDEX `USERS_ID` (`USERS_ID`),
	CONSTRAINT `FK_PERSONAL_MESSAGING_SETTINGS_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
