CREATE TABLE `PERSONAL_MESSAGE` (
	`PERSONAL_MESSAGE_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`PM_CONVERSATION_ID` INT(11) NOT NULL,
	`SENDER_ID` INT(11) NOT NULL,
	`RECEIVER_ID` INT(11) NULL DEFAULT NULL,
	`SENT_DT` DATETIME NOT NULL,
	`SUBJECT` TEXT NOT NULL,
	`MESSAGE` MEDIUMTEXT NOT NULL,
	`MESSAGE_PARSED` MEDIUMTEXT NOT NULL,
	`READ_FLAG` BIT(1) NULL DEFAULT b'0',
	`SEND_COPY_FLAG` BIT(1) NULL DEFAULT b'0',
	PRIMARY KEY (`PERSONAL_MESSAGE_ID`),
	INDEX `FK_PERSONAL_MESSAGE_ID_USERS_ID` (`SENDER_ID`),
	INDEX `FK_PERSONAL_MESSAGE_ID_RECEIVER_ID` (`RECEIVER_ID`),
	INDEX `FK_PERSONAL_MESSAGE_PM_CONVERSATION_ID` (`PM_CONVERSATION_ID`),
	CONSTRAINT `FK_PERSONAL_MESSAGE_ID_RECEIVER_ID` FOREIGN KEY (`RECEIVER_ID`) REFERENCES `users` (`USERS_ID`),
	CONSTRAINT `FK_PERSONAL_MESSAGE_ID_USERS_ID` FOREIGN KEY (`SENDER_ID`) REFERENCES `users` (`USERS_ID`),
	CONSTRAINT `FK_PERSONAL_MESSAGE_PM_CONVERSATION_ID` FOREIGN KEY (`PM_CONVERSATION_ID`) REFERENCES `PM_CONVERSATION` (`PM_CONVERSATION_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=204
;
