CREATE TABLE IF NOT EXISTS `PM_BACKUP_CODE` (
  `PM_BACKUP_CODE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERS_ID` int(11) NOT NULL,
  `ENCRYPTED_KEY_AES` varchar(32) NOT NULL,
  PRIMARY KEY (`PM_BACKUP_CODE_ID`),
  KEY `FK_PM_BACKUP_CODE_ID_USERS_ID` (`USERS_ID`),
  CONSTRAINT `FK_PM_BACKUP_CODE_ID_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;