CREATE TABLE IF NOT EXISTS `PM_CONVERSATION` (
  `PM_CONVERSATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `START_DT` datetime NOT NULL,
  `INITIATOR_ID` int(11) NOT NULL,
  PRIMARY KEY (`PM_CONVERSATION_ID`),
  KEY `FK_PM_CONVERSATION_INITATOR_ID` (`INITIATOR_ID`),
  CONSTRAINT `FK_PM_CONVERSATION_INITATOR_ID` FOREIGN KEY (`INITIATOR_ID`) REFERENCES `users` (`USERS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
