CREATE TABLE `POLL` (
	`POLL_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`QUESTION` VARCHAR(64) NOT NULL,
	`MAX_VOTES_PER_USER` TINYINT(3) UNSIGNED NOT NULL,
	`THREAD_ID` INT(11) NULL DEFAULT NULL,
	`RUN_FOR_DAYS` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
	`ALLOW_CHANGE` BIT(1) NOT NULL DEFAULT b'0',
	`RESULT_VISIBILITY_ID` INT(11) NOT NULL DEFAULT '0',
	`MULTIPLE_CHOICE_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (`POLL_ID`),
	INDEX `FK_POLL_THREAD_THREAD_ID` (`THREAD_ID`),
	INDEX `FK_POLL_LKUP_POLL_VISIBILITY_RESULT_VISIBILITY_ID` (`RESULT_VISIBILITY_ID`),
	CONSTRAINT `FK_POLL_LKUP_POLL_VISIBILITY_RESULT_VISIBILITY_ID` FOREIGN KEY (`RESULT_VISIBILITY_ID`) REFERENCES `LKUP_POLL_VISIBILITY` (`LKUP_POLL_VISIBILITY_ID`),
	CONSTRAINT `FK_POLL_THREAD_THREAD_ID` FOREIGN KEY (`THREAD_ID`) REFERENCES `THREAD` (`THREAD_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
