CREATE TABLE `POLL_OPTION` (
	`POLL_OPTION_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`POLL_ID` INT(11) NOT NULL,
	`OPTION_TEXT` VARCHAR(64) NOT NULL,
	PRIMARY KEY (`POLL_OPTION_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
