CREATE TABLE `POST_CONTENT` (
	`POST_CONTENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`THREAD_POST_ID` INT(11) NOT NULL,
	`POST_DATA` TEXT NOT NULL,
	`CREATED_TS` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`AUTHOR_ID` INT(11) NOT NULL,
	`CURRENT_FLAG` BIT(1) NOT NULL DEFAULT b'1',
	PRIMARY KEY (`POST_CONTENT_ID`),
	INDEX `POST_CONTENT_THREAD_POST_THREAD_POST_ID` (`THREAD_POST_ID`),
	INDEX `POST_CONTENT_USERS_AUTHOR_ID` (`AUTHOR_ID`),
	CONSTRAINT `POST_CONTENT_USERS_AUTHOR_ID` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `users` (`USERS_ID`),
	CONSTRAINT `POST_CONTENT_THREAD_POST_THREAD_POST_ID` FOREIGN KEY (`THREAD_POST_ID`) REFERENCES `THREAD_POST` (`THREAD_POST_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
