CREATE TABLE `SYSTEM_SETTINGS` (
	`SYSTEM_SETTING_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`VALUE` VARCHAR(50) NOT NULL,
	`CODE` VARCHAR(50) NOT NULL,
	`CREATED_TS` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_TS` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`SYSTEM_SETTING_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
