CREATE TABLE `THREAD_POST` (
	`THREAD_POST_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`THREAD_ID` INT(11) NOT NULL,
	`AUTHOR_ID` INT(11) NOT NULL,
	`CREATED_TS` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`THREAD_POST_ID`),
	INDEX `THREAD_POST_THREAD_THREAD_ID` (`THREAD_ID`),
	INDEX `THREAD_POST_USERS_AUTHOR_ID` (`AUTHOR_ID`),
	CONSTRAINT `THREAD_POST_THREAD_THREAD_ID` FOREIGN KEY (`THREAD_ID`) REFERENCES `THREAD` (`THREAD_ID`),
	CONSTRAINT `THREAD_POST_USERS_AUTHOR_ID` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `users` (`USERS_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=5
;
