CREATE TABLE `USER_CONTACT_SETTINGS` (
	`USER_CONTACT_SETTINGS_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`EMAIL_ADDRESS_ID` INT(11) NOT NULL,
	`USERS_ID` INT(10) NOT NULL DEFAULT '0',
	`GTALK` VARCHAR(32) NULL DEFAULT NULL,
	`SKYPE` VARCHAR(32) NULL DEFAULT NULL,
	`STEAM` VARCHAR(32) NULL DEFAULT NULL,
	`PSN` VARCHAR(32) NULL DEFAULT NULL,
	`NNID` VARCHAR(32) NULL DEFAULT NULL,
	`XBOX_LIVE` VARCHAR(32) NULL DEFAULT NULL,
	`FACEBOOK` VARCHAR(32) NULL DEFAULT NULL,
	PRIMARY KEY (`USER_CONTACT_SETTINGS_ID`),
	UNIQUE INDEX `USERS_ID` (`USERS_ID`),
	UNIQUE INDEX `EMAIL_ADDRESS_ID` (`EMAIL_ADDRESS_ID`),
	CONSTRAINT `FK_USER_CONTACT_SETTINGS_EMAIL_ADDRESS` FOREIGN KEY (`EMAIL_ADDRESS_ID`) REFERENCES `EMAIL_ADDRESS` (`EMAIL_ADDRESS_ID`),
	CONSTRAINT `FK_USER_CONTACT_SETTINGS_USERS` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=14
;
