CREATE TABLE `USER_SECURITY_SETTINGS` (
	`USER_SECURITY_SETTINGS_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USERS_ID` INT(11) NOT NULL,
	`HIDE_SKYPE_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`HIDE_GTALK_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`HIDE_STEAM_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`HIDE_NNID_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`HIDE_PSN_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`HIDE_XBOX_LIVE_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`HIDE_GENDER_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`HIDE_BIRTH_DATE_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`HIDE_EMAIL_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	PRIMARY KEY (`USER_SECURITY_SETTINGS_ID`),
	UNIQUE INDEX `USER_ID` (`USERS_ID`),
	CONSTRAINT `FK_USER_SECURITY_SETTINGS_USERS` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=5
;
