CREATE TABLE `USER_CURRENT_ACTION` (
	`USER_CURRENT_ACTION_ID` INT(11) NOT NULL,
	`USERS_ID` INT(11) NOT NULL,
	`LOCATION_ID` INT(11) NOT NULL,
	`CREATED_TS` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`UPDATED_TS` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`PARAM` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`USER_CURRENT_ACTION_ID`),
	INDEX `FK_USER_CURRENT_ACTION_ID_USERS_ID` (`USERS_ID`),
	INDEX `FK_USER_CURRENT_ACTION_ID_LOCATION_ID` (`LOCATION_ID`),
	CONSTRAINT `FK_USER_CURRENT_ACTION_ID_LOCATION_ID` FOREIGN KEY (`LOCATION_ID`) REFERENCES `LKUP_USER_ACTION` (`LKUP_USER_ACTION_ID`),
	CONSTRAINT `FK_USER_CURRENT_ACTION_ID_USERS_ID` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;