CREATE TABLE `LKUP_AVATAR_GALLERY` (
	`AVATAR_GALLERY_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`AVATAR_FILE_PATH` VARCHAR(256) NOT NULL,
	PRIMARY KEY (`AVATAR_GALLERY_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
