CREATE TABLE `LKUP_AVATAR_TYPE` (
	`AVATAR_TYPE_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`AVATAR_TYPE_DESC` VARCHAR(32) NOT NULL,
	PRIMARY KEY (`AVATAR_TYPE_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

INSERT INTO `LKUP_AVATAR_TYPE` (`AVATAR_TYPE_ID`, `AVATAR_TYPE_DESC`) VALUES
	(1, 'None'),
	(2, 'File Upload'),
	(3, 'External URL'),
	(4, 'Gallery');