CREATE TABLE IF NOT EXISTS `LKUP_PM_NOTIF` (
  `LKUP_PM_NOTIF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESC` varchar(16) DEFAULT '0',
  PRIMARY KEY (`LKUP_PM_NOTIF_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

DELETE FROM `LKUP_PM_NOTIF`;
INSERT INTO `LKUP_PM_NOTIF` (`LKUP_PM_NOTIF_ID`, `DESC`) VALUES
	(1, 'Always'),
	(2, 'Never'),
	(3, 'From Buddies');