CREATE TABLE `LKUP_NAV_SECTIONS` (
	`LKUP_NAV_SECTIONS_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`SECTION_CODE` CHAR(4) NOT NULL,
	PRIMARY KEY (`LKUP_NAV_SECTIONS_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=17
;

INSERT INTO `LKUP_NAV_SECTIONS` (`LKUP_NAV_SECTIONS_ID`, `SECTION_CODE`) VALUES
	(1, 'ACTS'),
	(2, 'FMPL'),
	(3, 'MDPL'),
	(4, 'MSGS'),
	(5, 'PLIN'),
	(6, 'SHST'),
	(7, 'SUMM'),
	(8, 'TRUS'),
	(9, 'NTST'),
	(10, 'PMST'),
	(11, 'BDIG');
