CREATE TABLE `LKUP_GENDER` (
	`GENDER_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`DESC` VARCHAR(10) NOT NULL,
	INDEX `GENDER_ID` (`GENDER_ID`)
)
ENGINE=InnoDB
;

INSERT INTO `LKUP_GENDER` (`GENDER_ID`, `DESC`) VALUES
	(1, 'Male'),
	(2, 'Female'),
	(3, 'Mayonnaise');