CREATE TABLE `LKUP_MEMBER_GROUP` (
	`MEMBER_GROUP_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`GROUP_NAME` VARCHAR(32) NULL DEFAULT NULL,
	`GROUP_DESC` VARCHAR(64) NULL DEFAULT NULL,
	`MIN_POSTS` INT(11) NULL DEFAULT NULL,
	`STARS_SPRITE` VARCHAR(64) NULL DEFAULT NULL,
	`HIDDEN_FLAG` BIT(1) NOT NULL DEFAULT b'0',
	`PARENT_GROUP` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`MEMBER_GROUP_ID`),
	INDEX `FK_LKUP_MEMBER_GROUP_LKUP_MEMBER_GROUP` (`PARENT_GROUP`),
	CONSTRAINT `FK_LKUP_MEMBER_GROUP_LKUP_MEMBER_GROUP` FOREIGN KEY (`PARENT_GROUP`) REFERENCES `LKUP_MEMBER_GROUP` (`MEMBER_GROUP_ID`) ON UPDATE CASCADE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
