CREATE TABLE `LKUP_POLL_VISIBILITY` (
	`LKUP_POLL_VISIBILITY_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`DESC` VARCHAR(64) NOT NULL,
	PRIMARY KEY (`LKUP_POLL_VISIBILITY_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
