package com.zfgc.dbobj;

public class brMemberGroupForumDbObjKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BR_MEMBER_GROUP_FORUM.FORUM_ID
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    private Short forumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BR_MEMBER_GROUP_FORUM.MEMBER_GROUP_ID
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    private Integer memberGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BR_MEMBER_GROUP_FORUM.FORUM_ID
     *
     * @return the value of BR_MEMBER_GROUP_FORUM.FORUM_ID
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    public Short getForumId() {
        return forumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BR_MEMBER_GROUP_FORUM.FORUM_ID
     *
     * @param forumId the value for BR_MEMBER_GROUP_FORUM.FORUM_ID
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    public void setForumId(Short forumId) {
        this.forumId = forumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BR_MEMBER_GROUP_FORUM.MEMBER_GROUP_ID
     *
     * @return the value of BR_MEMBER_GROUP_FORUM.MEMBER_GROUP_ID
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    public Integer getMemberGroupId() {
        return memberGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BR_MEMBER_GROUP_FORUM.MEMBER_GROUP_ID
     *
     * @param memberGroupId the value for BR_MEMBER_GROUP_FORUM.MEMBER_GROUP_ID
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    public void setMemberGroupId(Integer memberGroupId) {
        this.memberGroupId = memberGroupId;
    }
}