package com.zfgc.dbobj;

public class brMemberGroupForumDbObj extends brMemberGroupForumDbObjKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BR_MEMBER_GROUP_FORUM.READ_FLAG
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    private Boolean readFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BR_MEMBER_GROUP_FORUM.WRITE_FLAG
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    private Boolean writeFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BR_MEMBER_GROUP_FORUM.READ_FLAG
     *
     * @return the value of BR_MEMBER_GROUP_FORUM.READ_FLAG
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    public Boolean getReadFlag() {
        return readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BR_MEMBER_GROUP_FORUM.READ_FLAG
     *
     * @param readFlag the value for BR_MEMBER_GROUP_FORUM.READ_FLAG
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    public void setReadFlag(Boolean readFlag) {
        this.readFlag = readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BR_MEMBER_GROUP_FORUM.WRITE_FLAG
     *
     * @return the value of BR_MEMBER_GROUP_FORUM.WRITE_FLAG
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    public Boolean getWriteFlag() {
        return writeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BR_MEMBER_GROUP_FORUM.WRITE_FLAG
     *
     * @param writeFlag the value for BR_MEMBER_GROUP_FORUM.WRITE_FLAG
     *
     * @mbggenerated Mon Dec 26 19:42:36 EST 2016
     */
    public void setWriteFlag(Boolean writeFlag) {
        this.writeFlag = writeFlag;
    }
}