package com.zfgc.dbobj;

import java.util.Date;

public class outboxViewDbObj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTBOX_VIEW.PERSONAL_MESSAGE_ID
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    private Integer personalMessageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTBOX_VIEW.SENDER_ID
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    private Integer senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTBOX_VIEW.RECEIVER_ID
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    private Integer receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTBOX_VIEW.SENT_DT
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    private Date sentDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTBOX_VIEW.READ_FLAG
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    private Boolean readFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTBOX_VIEW.PERSONAL_MESSAGE_ID
     *
     * @return the value of OUTBOX_VIEW.PERSONAL_MESSAGE_ID
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    public Integer getPersonalMessageId() {
        return personalMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OUTBOX_VIEW.PERSONAL_MESSAGE_ID
     *
     * @param personalMessageId the value for OUTBOX_VIEW.PERSONAL_MESSAGE_ID
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    public void setPersonalMessageId(Integer personalMessageId) {
        this.personalMessageId = personalMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTBOX_VIEW.SENDER_ID
     *
     * @return the value of OUTBOX_VIEW.SENDER_ID
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OUTBOX_VIEW.SENDER_ID
     *
     * @param senderId the value for OUTBOX_VIEW.SENDER_ID
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTBOX_VIEW.RECEIVER_ID
     *
     * @return the value of OUTBOX_VIEW.RECEIVER_ID
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OUTBOX_VIEW.RECEIVER_ID
     *
     * @param receiverId the value for OUTBOX_VIEW.RECEIVER_ID
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTBOX_VIEW.SENT_DT
     *
     * @return the value of OUTBOX_VIEW.SENT_DT
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    public Date getSentDt() {
        return sentDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OUTBOX_VIEW.SENT_DT
     *
     * @param sentDt the value for OUTBOX_VIEW.SENT_DT
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    public void setSentDt(Date sentDt) {
        this.sentDt = sentDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTBOX_VIEW.READ_FLAG
     *
     * @return the value of OUTBOX_VIEW.READ_FLAG
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    public Boolean getReadFlag() {
        return readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OUTBOX_VIEW.READ_FLAG
     *
     * @param readFlag the value for OUTBOX_VIEW.READ_FLAG
     *
     * @mbggenerated Sun Aug 27 16:37:01 EDT 2017
     */
    public void setReadFlag(Boolean readFlag) {
        this.readFlag = readFlag;
    }
}