package com.zfgc.dbobj;

public class SystemDirectoryDbObj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_ID
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    private Integer systemDirectoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_CODE
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    private String systemDirectoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_DESC
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    private String systemDirectoryDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DIRECTORIES.SYSTEM_PATH
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    private String systemPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_ID
     *
     * @return the value of SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_ID
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    public Integer getSystemDirectoryId() {
        return systemDirectoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_ID
     *
     * @param systemDirectoryId the value for SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_ID
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    public void setSystemDirectoryId(Integer systemDirectoryId) {
        this.systemDirectoryId = systemDirectoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_CODE
     *
     * @return the value of SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_CODE
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    public String getSystemDirectoryCode() {
        return systemDirectoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_CODE
     *
     * @param systemDirectoryCode the value for SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_CODE
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    public void setSystemDirectoryCode(String systemDirectoryCode) {
        this.systemDirectoryCode = systemDirectoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_DESC
     *
     * @return the value of SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_DESC
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    public String getSystemDirectoryDesc() {
        return systemDirectoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_DESC
     *
     * @param systemDirectoryDesc the value for SYSTEM_DIRECTORIES.SYSTEM_DIRECTORY_DESC
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    public void setSystemDirectoryDesc(String systemDirectoryDesc) {
        this.systemDirectoryDesc = systemDirectoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DIRECTORIES.SYSTEM_PATH
     *
     * @return the value of SYSTEM_DIRECTORIES.SYSTEM_PATH
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    public String getSystemPath() {
        return systemPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DIRECTORIES.SYSTEM_PATH
     *
     * @param systemPath the value for SYSTEM_DIRECTORIES.SYSTEM_PATH
     *
     * @mbg.generated Sun Jun 09 19:11:42 EDT 2019
     */
    public void setSystemPath(String systemPath) {
        this.systemPath = systemPath;
    }
}