package com.zfgc.dbobj;

import java.util.ArrayList;
import java.util.List;

public class UserConnectionDbObjExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public UserConnectionDbObjExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserConnectionIdIsNull() {
			addCriterion("USER_CONNECTION_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdIsNotNull() {
			addCriterion("USER_CONNECTION_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdEqualTo(Integer value) {
			addCriterion("USER_CONNECTION_ID =", value, "userConnectionId");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdNotEqualTo(Integer value) {
			addCriterion("USER_CONNECTION_ID <>", value, "userConnectionId");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdGreaterThan(Integer value) {
			addCriterion("USER_CONNECTION_ID >", value, "userConnectionId");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("USER_CONNECTION_ID >=", value, "userConnectionId");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdLessThan(Integer value) {
			addCriterion("USER_CONNECTION_ID <", value, "userConnectionId");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdLessThanOrEqualTo(Integer value) {
			addCriterion("USER_CONNECTION_ID <=", value, "userConnectionId");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdIn(List<Integer> values) {
			addCriterion("USER_CONNECTION_ID in", values, "userConnectionId");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdNotIn(List<Integer> values) {
			addCriterion("USER_CONNECTION_ID not in", values, "userConnectionId");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdBetween(Integer value1, Integer value2) {
			addCriterion("USER_CONNECTION_ID between", value1, value2, "userConnectionId");
			return (Criteria) this;
		}

		public Criteria andUserConnectionIdNotBetween(Integer value1, Integer value2) {
			addCriterion("USER_CONNECTION_ID not between", value1, value2, "userConnectionId");
			return (Criteria) this;
		}

		public Criteria andUsersIdIsNull() {
			addCriterion("USERS_ID is null");
			return (Criteria) this;
		}

		public Criteria andUsersIdIsNotNull() {
			addCriterion("USERS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUsersIdEqualTo(Integer value) {
			addCriterion("USERS_ID =", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdNotEqualTo(Integer value) {
			addCriterion("USERS_ID <>", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdGreaterThan(Integer value) {
			addCriterion("USERS_ID >", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("USERS_ID >=", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdLessThan(Integer value) {
			addCriterion("USERS_ID <", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdLessThanOrEqualTo(Integer value) {
			addCriterion("USERS_ID <=", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdIn(List<Integer> values) {
			addCriterion("USERS_ID in", values, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdNotIn(List<Integer> values) {
			addCriterion("USERS_ID not in", values, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdBetween(Integer value1, Integer value2) {
			addCriterion("USERS_ID between", value1, value2, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdNotBetween(Integer value1, Integer value2) {
			addCriterion("USERS_ID not between", value1, value2, "usersId");
			return (Criteria) this;
		}

		public Criteria andAgentVersionIsNull() {
			addCriterion("AGENT_VERSION is null");
			return (Criteria) this;
		}

		public Criteria andAgentVersionIsNotNull() {
			addCriterion("AGENT_VERSION is not null");
			return (Criteria) this;
		}

		public Criteria andAgentVersionEqualTo(String value) {
			addCriterion("AGENT_VERSION =", value, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionNotEqualTo(String value) {
			addCriterion("AGENT_VERSION <>", value, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionGreaterThan(String value) {
			addCriterion("AGENT_VERSION >", value, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_VERSION >=", value, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionLessThan(String value) {
			addCriterion("AGENT_VERSION <", value, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionLessThanOrEqualTo(String value) {
			addCriterion("AGENT_VERSION <=", value, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionLike(String value) {
			addCriterion("AGENT_VERSION like", value, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionNotLike(String value) {
			addCriterion("AGENT_VERSION not like", value, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionIn(List<String> values) {
			addCriterion("AGENT_VERSION in", values, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionNotIn(List<String> values) {
			addCriterion("AGENT_VERSION not in", values, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionBetween(String value1, String value2) {
			addCriterion("AGENT_VERSION between", value1, value2, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentVersionNotBetween(String value1, String value2) {
			addCriterion("AGENT_VERSION not between", value1, value2, "agentVersion");
			return (Criteria) this;
		}

		public Criteria andAgentTypeIsNull() {
			addCriterion("AGENT_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andAgentTypeIsNotNull() {
			addCriterion("AGENT_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andAgentTypeEqualTo(String value) {
			addCriterion("AGENT_TYPE =", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotEqualTo(String value) {
			addCriterion("AGENT_TYPE <>", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeGreaterThan(String value) {
			addCriterion("AGENT_TYPE >", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_TYPE >=", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeLessThan(String value) {
			addCriterion("AGENT_TYPE <", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeLessThanOrEqualTo(String value) {
			addCriterion("AGENT_TYPE <=", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeLike(String value) {
			addCriterion("AGENT_TYPE like", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotLike(String value) {
			addCriterion("AGENT_TYPE not like", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeIn(List<String> values) {
			addCriterion("AGENT_TYPE in", values, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotIn(List<String> values) {
			addCriterion("AGENT_TYPE not in", values, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeBetween(String value1, String value2) {
			addCriterion("AGENT_TYPE between", value1, value2, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotBetween(String value1, String value2) {
			addCriterion("AGENT_TYPE not between", value1, value2, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentNameIsNull() {
			addCriterion("AGENT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andAgentNameIsNotNull() {
			addCriterion("AGENT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andAgentNameEqualTo(String value) {
			addCriterion("AGENT_NAME =", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameNotEqualTo(String value) {
			addCriterion("AGENT_NAME <>", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameGreaterThan(String value) {
			addCriterion("AGENT_NAME >", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_NAME >=", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameLessThan(String value) {
			addCriterion("AGENT_NAME <", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameLessThanOrEqualTo(String value) {
			addCriterion("AGENT_NAME <=", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameLike(String value) {
			addCriterion("AGENT_NAME like", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameNotLike(String value) {
			addCriterion("AGENT_NAME not like", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameIn(List<String> values) {
			addCriterion("AGENT_NAME in", values, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameNotIn(List<String> values) {
			addCriterion("AGENT_NAME not in", values, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameBetween(String value1, String value2) {
			addCriterion("AGENT_NAME between", value1, value2, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameNotBetween(String value1, String value2) {
			addCriterion("AGENT_NAME not between", value1, value2, "agentName");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdIsNull() {
			addCriterion("IP_ADDRESS_ID is null");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdIsNotNull() {
			addCriterion("IP_ADDRESS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdEqualTo(Integer value) {
			addCriterion("IP_ADDRESS_ID =", value, "ipAddressId");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdNotEqualTo(Integer value) {
			addCriterion("IP_ADDRESS_ID <>", value, "ipAddressId");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdGreaterThan(Integer value) {
			addCriterion("IP_ADDRESS_ID >", value, "ipAddressId");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("IP_ADDRESS_ID >=", value, "ipAddressId");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdLessThan(Integer value) {
			addCriterion("IP_ADDRESS_ID <", value, "ipAddressId");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdLessThanOrEqualTo(Integer value) {
			addCriterion("IP_ADDRESS_ID <=", value, "ipAddressId");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdIn(List<Integer> values) {
			addCriterion("IP_ADDRESS_ID in", values, "ipAddressId");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdNotIn(List<Integer> values) {
			addCriterion("IP_ADDRESS_ID not in", values, "ipAddressId");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdBetween(Integer value1, Integer value2) {
			addCriterion("IP_ADDRESS_ID between", value1, value2, "ipAddressId");
			return (Criteria) this;
		}

		public Criteria andIpAddressIdNotBetween(Integer value1, Integer value2) {
			addCriterion("IP_ADDRESS_ID not between", value1, value2, "ipAddressId");
			return (Criteria) this;
		}

		public Criteria andUserAgentIsNull() {
			addCriterion("USER_AGENT is null");
			return (Criteria) this;
		}

		public Criteria andUserAgentIsNotNull() {
			addCriterion("USER_AGENT is not null");
			return (Criteria) this;
		}

		public Criteria andUserAgentEqualTo(String value) {
			addCriterion("USER_AGENT =", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentNotEqualTo(String value) {
			addCriterion("USER_AGENT <>", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentGreaterThan(String value) {
			addCriterion("USER_AGENT >", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentGreaterThanOrEqualTo(String value) {
			addCriterion("USER_AGENT >=", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentLessThan(String value) {
			addCriterion("USER_AGENT <", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentLessThanOrEqualTo(String value) {
			addCriterion("USER_AGENT <=", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentLike(String value) {
			addCriterion("USER_AGENT like", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentNotLike(String value) {
			addCriterion("USER_AGENT not like", value, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentIn(List<String> values) {
			addCriterion("USER_AGENT in", values, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentNotIn(List<String> values) {
			addCriterion("USER_AGENT not in", values, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentBetween(String value1, String value2) {
			addCriterion("USER_AGENT between", value1, value2, "userAgent");
			return (Criteria) this;
		}

		public Criteria andUserAgentNotBetween(String value1, String value2) {
			addCriterion("USER_AGENT not between", value1, value2, "userAgent");
			return (Criteria) this;
		}

		public Criteria andOsTypeIsNull() {
			addCriterion("OS_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andOsTypeIsNotNull() {
			addCriterion("OS_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andOsTypeEqualTo(String value) {
			addCriterion("OS_TYPE =", value, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeNotEqualTo(String value) {
			addCriterion("OS_TYPE <>", value, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeGreaterThan(String value) {
			addCriterion("OS_TYPE >", value, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeGreaterThanOrEqualTo(String value) {
			addCriterion("OS_TYPE >=", value, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeLessThan(String value) {
			addCriterion("OS_TYPE <", value, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeLessThanOrEqualTo(String value) {
			addCriterion("OS_TYPE <=", value, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeLike(String value) {
			addCriterion("OS_TYPE like", value, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeNotLike(String value) {
			addCriterion("OS_TYPE not like", value, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeIn(List<String> values) {
			addCriterion("OS_TYPE in", values, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeNotIn(List<String> values) {
			addCriterion("OS_TYPE not in", values, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeBetween(String value1, String value2) {
			addCriterion("OS_TYPE between", value1, value2, "osType");
			return (Criteria) this;
		}

		public Criteria andOsTypeNotBetween(String value1, String value2) {
			addCriterion("OS_TYPE not between", value1, value2, "osType");
			return (Criteria) this;
		}

		public Criteria andOsNameIsNull() {
			addCriterion("OS_NAME is null");
			return (Criteria) this;
		}

		public Criteria andOsNameIsNotNull() {
			addCriterion("OS_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andOsNameEqualTo(String value) {
			addCriterion("OS_NAME =", value, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameNotEqualTo(String value) {
			addCriterion("OS_NAME <>", value, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameGreaterThan(String value) {
			addCriterion("OS_NAME >", value, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameGreaterThanOrEqualTo(String value) {
			addCriterion("OS_NAME >=", value, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameLessThan(String value) {
			addCriterion("OS_NAME <", value, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameLessThanOrEqualTo(String value) {
			addCriterion("OS_NAME <=", value, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameLike(String value) {
			addCriterion("OS_NAME like", value, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameNotLike(String value) {
			addCriterion("OS_NAME not like", value, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameIn(List<String> values) {
			addCriterion("OS_NAME in", values, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameNotIn(List<String> values) {
			addCriterion("OS_NAME not in", values, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameBetween(String value1, String value2) {
			addCriterion("OS_NAME between", value1, value2, "osName");
			return (Criteria) this;
		}

		public Criteria andOsNameNotBetween(String value1, String value2) {
			addCriterion("OS_NAME not between", value1, value2, "osName");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameIsNull() {
			addCriterion("OS_VERSIONNAME is null");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameIsNotNull() {
			addCriterion("OS_VERSIONNAME is not null");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameEqualTo(String value) {
			addCriterion("OS_VERSIONNAME =", value, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameNotEqualTo(String value) {
			addCriterion("OS_VERSIONNAME <>", value, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameGreaterThan(String value) {
			addCriterion("OS_VERSIONNAME >", value, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameGreaterThanOrEqualTo(String value) {
			addCriterion("OS_VERSIONNAME >=", value, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameLessThan(String value) {
			addCriterion("OS_VERSIONNAME <", value, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameLessThanOrEqualTo(String value) {
			addCriterion("OS_VERSIONNAME <=", value, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameLike(String value) {
			addCriterion("OS_VERSIONNAME like", value, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameNotLike(String value) {
			addCriterion("OS_VERSIONNAME not like", value, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameIn(List<String> values) {
			addCriterion("OS_VERSIONNAME in", values, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameNotIn(List<String> values) {
			addCriterion("OS_VERSIONNAME not in", values, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameBetween(String value1, String value2) {
			addCriterion("OS_VERSIONNAME between", value1, value2, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnameNotBetween(String value1, String value2) {
			addCriterion("OS_VERSIONNAME not between", value1, value2, "osVersionname");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberIsNull() {
			addCriterion("OS_VERSIONNUMBER is null");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberIsNotNull() {
			addCriterion("OS_VERSIONNUMBER is not null");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberEqualTo(String value) {
			addCriterion("OS_VERSIONNUMBER =", value, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberNotEqualTo(String value) {
			addCriterion("OS_VERSIONNUMBER <>", value, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberGreaterThan(String value) {
			addCriterion("OS_VERSIONNUMBER >", value, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberGreaterThanOrEqualTo(String value) {
			addCriterion("OS_VERSIONNUMBER >=", value, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberLessThan(String value) {
			addCriterion("OS_VERSIONNUMBER <", value, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberLessThanOrEqualTo(String value) {
			addCriterion("OS_VERSIONNUMBER <=", value, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberLike(String value) {
			addCriterion("OS_VERSIONNUMBER like", value, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberNotLike(String value) {
			addCriterion("OS_VERSIONNUMBER not like", value, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberIn(List<String> values) {
			addCriterion("OS_VERSIONNUMBER in", values, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberNotIn(List<String> values) {
			addCriterion("OS_VERSIONNUMBER not in", values, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberBetween(String value1, String value2) {
			addCriterion("OS_VERSIONNUMBER between", value1, value2, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andOsVersionnumberNotBetween(String value1, String value2) {
			addCriterion("OS_VERSIONNUMBER not between", value1, value2, "osVersionnumber");
			return (Criteria) this;
		}

		public Criteria andSessionIdIsNull() {
			addCriterion("SESSION_ID is null");
			return (Criteria) this;
		}

		public Criteria andSessionIdIsNotNull() {
			addCriterion("SESSION_ID is not null");
			return (Criteria) this;
		}

		public Criteria andSessionIdEqualTo(String value) {
			addCriterion("SESSION_ID =", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdNotEqualTo(String value) {
			addCriterion("SESSION_ID <>", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdGreaterThan(String value) {
			addCriterion("SESSION_ID >", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
			addCriterion("SESSION_ID >=", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdLessThan(String value) {
			addCriterion("SESSION_ID <", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdLessThanOrEqualTo(String value) {
			addCriterion("SESSION_ID <=", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdLike(String value) {
			addCriterion("SESSION_ID like", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdNotLike(String value) {
			addCriterion("SESSION_ID not like", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdIn(List<String> values) {
			addCriterion("SESSION_ID in", values, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdNotIn(List<String> values) {
			addCriterion("SESSION_ID not in", values, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdBetween(String value1, String value2) {
			addCriterion("SESSION_ID between", value1, value2, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdNotBetween(String value1, String value2) {
			addCriterion("SESSION_ID not between", value1, value2, "sessionId");
			return (Criteria) this;
		}

		public Criteria andUserActionIdIsNull() {
			addCriterion("USER_ACTION_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserActionIdIsNotNull() {
			addCriterion("USER_ACTION_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserActionIdEqualTo(Integer value) {
			addCriterion("USER_ACTION_ID =", value, "userActionId");
			return (Criteria) this;
		}

		public Criteria andUserActionIdNotEqualTo(Integer value) {
			addCriterion("USER_ACTION_ID <>", value, "userActionId");
			return (Criteria) this;
		}

		public Criteria andUserActionIdGreaterThan(Integer value) {
			addCriterion("USER_ACTION_ID >", value, "userActionId");
			return (Criteria) this;
		}

		public Criteria andUserActionIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("USER_ACTION_ID >=", value, "userActionId");
			return (Criteria) this;
		}

		public Criteria andUserActionIdLessThan(Integer value) {
			addCriterion("USER_ACTION_ID <", value, "userActionId");
			return (Criteria) this;
		}

		public Criteria andUserActionIdLessThanOrEqualTo(Integer value) {
			addCriterion("USER_ACTION_ID <=", value, "userActionId");
			return (Criteria) this;
		}

		public Criteria andUserActionIdIn(List<Integer> values) {
			addCriterion("USER_ACTION_ID in", values, "userActionId");
			return (Criteria) this;
		}

		public Criteria andUserActionIdNotIn(List<Integer> values) {
			addCriterion("USER_ACTION_ID not in", values, "userActionId");
			return (Criteria) this;
		}

		public Criteria andUserActionIdBetween(Integer value1, Integer value2) {
			addCriterion("USER_ACTION_ID between", value1, value2, "userActionId");
			return (Criteria) this;
		}

		public Criteria andUserActionIdNotBetween(Integer value1, Integer value2) {
			addCriterion("USER_ACTION_ID not between", value1, value2, "userActionId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table USER_CONNECTION
	 * @mbg.generated  Sat Jan 25 10:32:56 EST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_CONNECTION
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 11 21:43:23 EDT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}