package com.zfgc.dbobj;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsersDbObjExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public UsersDbObjExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUsersIdIsNull() {
			addCriterion("USERS_ID is null");
			return (Criteria) this;
		}

		public Criteria andUsersIdIsNotNull() {
			addCriterion("USERS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUsersIdEqualTo(Integer value) {
			addCriterion("USERS_ID =", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdNotEqualTo(Integer value) {
			addCriterion("USERS_ID <>", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdGreaterThan(Integer value) {
			addCriterion("USERS_ID >", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("USERS_ID >=", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdLessThan(Integer value) {
			addCriterion("USERS_ID <", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdLessThanOrEqualTo(Integer value) {
			addCriterion("USERS_ID <=", value, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdIn(List<Integer> values) {
			addCriterion("USERS_ID in", values, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdNotIn(List<Integer> values) {
			addCriterion("USERS_ID not in", values, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdBetween(Integer value1, Integer value2) {
			addCriterion("USERS_ID between", value1, value2, "usersId");
			return (Criteria) this;
		}

		public Criteria andUsersIdNotBetween(Integer value1, Integer value2) {
			addCriterion("USERS_ID not between", value1, value2, "usersId");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdIsNull() {
			addCriterion("PRIMARY_MEMBER_GROUP_ID is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdIsNotNull() {
			addCriterion("PRIMARY_MEMBER_GROUP_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdEqualTo(Integer value) {
			addCriterion("PRIMARY_MEMBER_GROUP_ID =", value, "primaryMemberGroupId");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdNotEqualTo(Integer value) {
			addCriterion("PRIMARY_MEMBER_GROUP_ID <>", value, "primaryMemberGroupId");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdGreaterThan(Integer value) {
			addCriterion("PRIMARY_MEMBER_GROUP_ID >", value, "primaryMemberGroupId");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PRIMARY_MEMBER_GROUP_ID >=", value, "primaryMemberGroupId");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdLessThan(Integer value) {
			addCriterion("PRIMARY_MEMBER_GROUP_ID <", value, "primaryMemberGroupId");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdLessThanOrEqualTo(Integer value) {
			addCriterion("PRIMARY_MEMBER_GROUP_ID <=", value, "primaryMemberGroupId");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdIn(List<Integer> values) {
			addCriterion("PRIMARY_MEMBER_GROUP_ID in", values, "primaryMemberGroupId");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdNotIn(List<Integer> values) {
			addCriterion("PRIMARY_MEMBER_GROUP_ID not in", values, "primaryMemberGroupId");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdBetween(Integer value1, Integer value2) {
			addCriterion("PRIMARY_MEMBER_GROUP_ID between", value1, value2, "primaryMemberGroupId");
			return (Criteria) this;
		}

		public Criteria andPrimaryMemberGroupIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PRIMARY_MEMBER_GROUP_ID not between", value1, value2, "primaryMemberGroupId");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpIsNull() {
			addCriterion("PRIMARY_IP is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpIsNotNull() {
			addCriterion("PRIMARY_IP is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpEqualTo(String value) {
			addCriterion("PRIMARY_IP =", value, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpNotEqualTo(String value) {
			addCriterion("PRIMARY_IP <>", value, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpGreaterThan(String value) {
			addCriterion("PRIMARY_IP >", value, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpGreaterThanOrEqualTo(String value) {
			addCriterion("PRIMARY_IP >=", value, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpLessThan(String value) {
			addCriterion("PRIMARY_IP <", value, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpLessThanOrEqualTo(String value) {
			addCriterion("PRIMARY_IP <=", value, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpLike(String value) {
			addCriterion("PRIMARY_IP like", value, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpNotLike(String value) {
			addCriterion("PRIMARY_IP not like", value, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpIn(List<String> values) {
			addCriterion("PRIMARY_IP in", values, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpNotIn(List<String> values) {
			addCriterion("PRIMARY_IP not in", values, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpBetween(String value1, String value2) {
			addCriterion("PRIMARY_IP between", value1, value2, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andPrimaryIpNotBetween(String value1, String value2) {
			addCriterion("PRIMARY_IP not between", value1, value2, "primaryIp");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNull() {
			addCriterion("LOGIN_NAME is null");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNotNull() {
			addCriterion("LOGIN_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andLoginNameEqualTo(String value) {
			addCriterion("LOGIN_NAME =", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotEqualTo(String value) {
			addCriterion("LOGIN_NAME <>", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThan(String value) {
			addCriterion("LOGIN_NAME >", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
			addCriterion("LOGIN_NAME >=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThan(String value) {
			addCriterion("LOGIN_NAME <", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThanOrEqualTo(String value) {
			addCriterion("LOGIN_NAME <=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLike(String value) {
			addCriterion("LOGIN_NAME like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotLike(String value) {
			addCriterion("LOGIN_NAME not like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameIn(List<String> values) {
			addCriterion("LOGIN_NAME in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotIn(List<String> values) {
			addCriterion("LOGIN_NAME not in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameBetween(String value1, String value2) {
			addCriterion("LOGIN_NAME between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotBetween(String value1, String value2) {
			addCriterion("LOGIN_NAME not between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameIsNull() {
			addCriterion("DISPLAY_NAME is null");
			return (Criteria) this;
		}

		public Criteria andDisplayNameIsNotNull() {
			addCriterion("DISPLAY_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andDisplayNameEqualTo(String value) {
			addCriterion("DISPLAY_NAME =", value, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameNotEqualTo(String value) {
			addCriterion("DISPLAY_NAME <>", value, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameGreaterThan(String value) {
			addCriterion("DISPLAY_NAME >", value, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameGreaterThanOrEqualTo(String value) {
			addCriterion("DISPLAY_NAME >=", value, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameLessThan(String value) {
			addCriterion("DISPLAY_NAME <", value, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameLessThanOrEqualTo(String value) {
			addCriterion("DISPLAY_NAME <=", value, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameLike(String value) {
			addCriterion("DISPLAY_NAME like", value, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameNotLike(String value) {
			addCriterion("DISPLAY_NAME not like", value, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameIn(List<String> values) {
			addCriterion("DISPLAY_NAME in", values, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameNotIn(List<String> values) {
			addCriterion("DISPLAY_NAME not in", values, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameBetween(String value1, String value2) {
			addCriterion("DISPLAY_NAME between", value1, value2, "displayName");
			return (Criteria) this;
		}

		public Criteria andDisplayNameNotBetween(String value1, String value2) {
			addCriterion("DISPLAY_NAME not between", value1, value2, "displayName");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("PASSWORD in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("PASSWORD not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPassSaltIsNull() {
			addCriterion("PASS_SALT is null");
			return (Criteria) this;
		}

		public Criteria andPassSaltIsNotNull() {
			addCriterion("PASS_SALT is not null");
			return (Criteria) this;
		}

		public Criteria andPassSaltEqualTo(String value) {
			addCriterion("PASS_SALT =", value, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltNotEqualTo(String value) {
			addCriterion("PASS_SALT <>", value, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltGreaterThan(String value) {
			addCriterion("PASS_SALT >", value, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltGreaterThanOrEqualTo(String value) {
			addCriterion("PASS_SALT >=", value, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltLessThan(String value) {
			addCriterion("PASS_SALT <", value, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltLessThanOrEqualTo(String value) {
			addCriterion("PASS_SALT <=", value, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltLike(String value) {
			addCriterion("PASS_SALT like", value, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltNotLike(String value) {
			addCriterion("PASS_SALT not like", value, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltIn(List<String> values) {
			addCriterion("PASS_SALT in", values, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltNotIn(List<String> values) {
			addCriterion("PASS_SALT not in", values, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltBetween(String value1, String value2) {
			addCriterion("PASS_SALT between", value1, value2, "passSalt");
			return (Criteria) this;
		}

		public Criteria andPassSaltNotBetween(String value1, String value2) {
			addCriterion("PASS_SALT not between", value1, value2, "passSalt");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredIsNull() {
			addCriterion("DATE_REGISTERED is null");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredIsNotNull() {
			addCriterion("DATE_REGISTERED is not null");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredEqualTo(Date value) {
			addCriterion("DATE_REGISTERED =", value, "dateRegistered");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredNotEqualTo(Date value) {
			addCriterion("DATE_REGISTERED <>", value, "dateRegistered");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredGreaterThan(Date value) {
			addCriterion("DATE_REGISTERED >", value, "dateRegistered");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredGreaterThanOrEqualTo(Date value) {
			addCriterion("DATE_REGISTERED >=", value, "dateRegistered");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredLessThan(Date value) {
			addCriterion("DATE_REGISTERED <", value, "dateRegistered");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredLessThanOrEqualTo(Date value) {
			addCriterion("DATE_REGISTERED <=", value, "dateRegistered");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredIn(List<Date> values) {
			addCriterion("DATE_REGISTERED in", values, "dateRegistered");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredNotIn(List<Date> values) {
			addCriterion("DATE_REGISTERED not in", values, "dateRegistered");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredBetween(Date value1, Date value2) {
			addCriterion("DATE_REGISTERED between", value1, value2, "dateRegistered");
			return (Criteria) this;
		}

		public Criteria andDateRegisteredNotBetween(Date value1, Date value2) {
			addCriterion("DATE_REGISTERED not between", value1, value2, "dateRegistered");
			return (Criteria) this;
		}

		public Criteria andLanguageIsNull() {
			addCriterion("LANGUAGE is null");
			return (Criteria) this;
		}

		public Criteria andLanguageIsNotNull() {
			addCriterion("LANGUAGE is not null");
			return (Criteria) this;
		}

		public Criteria andLanguageEqualTo(Integer value) {
			addCriterion("LANGUAGE =", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageNotEqualTo(Integer value) {
			addCriterion("LANGUAGE <>", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageGreaterThan(Integer value) {
			addCriterion("LANGUAGE >", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageGreaterThanOrEqualTo(Integer value) {
			addCriterion("LANGUAGE >=", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageLessThan(Integer value) {
			addCriterion("LANGUAGE <", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageLessThanOrEqualTo(Integer value) {
			addCriterion("LANGUAGE <=", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageIn(List<Integer> values) {
			addCriterion("LANGUAGE in", values, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageNotIn(List<Integer> values) {
			addCriterion("LANGUAGE not in", values, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageBetween(Integer value1, Integer value2) {
			addCriterion("LANGUAGE between", value1, value2, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageNotBetween(Integer value1, Integer value2) {
			addCriterion("LANGUAGE not between", value1, value2, "language");
			return (Criteria) this;
		}

		public Criteria andLastLoginIsNull() {
			addCriterion("LAST_LOGIN is null");
			return (Criteria) this;
		}

		public Criteria andLastLoginIsNotNull() {
			addCriterion("LAST_LOGIN is not null");
			return (Criteria) this;
		}

		public Criteria andLastLoginEqualTo(Date value) {
			addCriterion("LAST_LOGIN =", value, "lastLogin");
			return (Criteria) this;
		}

		public Criteria andLastLoginNotEqualTo(Date value) {
			addCriterion("LAST_LOGIN <>", value, "lastLogin");
			return (Criteria) this;
		}

		public Criteria andLastLoginGreaterThan(Date value) {
			addCriterion("LAST_LOGIN >", value, "lastLogin");
			return (Criteria) this;
		}

		public Criteria andLastLoginGreaterThanOrEqualTo(Date value) {
			addCriterion("LAST_LOGIN >=", value, "lastLogin");
			return (Criteria) this;
		}

		public Criteria andLastLoginLessThan(Date value) {
			addCriterion("LAST_LOGIN <", value, "lastLogin");
			return (Criteria) this;
		}

		public Criteria andLastLoginLessThanOrEqualTo(Date value) {
			addCriterion("LAST_LOGIN <=", value, "lastLogin");
			return (Criteria) this;
		}

		public Criteria andLastLoginIn(List<Date> values) {
			addCriterion("LAST_LOGIN in", values, "lastLogin");
			return (Criteria) this;
		}

		public Criteria andLastLoginNotIn(List<Date> values) {
			addCriterion("LAST_LOGIN not in", values, "lastLogin");
			return (Criteria) this;
		}

		public Criteria andLastLoginBetween(Date value1, Date value2) {
			addCriterion("LAST_LOGIN between", value1, value2, "lastLogin");
			return (Criteria) this;
		}

		public Criteria andLastLoginNotBetween(Date value1, Date value2) {
			addCriterion("LAST_LOGIN not between", value1, value2, "lastLogin");
			return (Criteria) this;
		}

		public Criteria andPersonalTextIsNull() {
			addCriterion("PERSONAL_TEXT is null");
			return (Criteria) this;
		}

		public Criteria andPersonalTextIsNotNull() {
			addCriterion("PERSONAL_TEXT is not null");
			return (Criteria) this;
		}

		public Criteria andPersonalTextEqualTo(String value) {
			addCriterion("PERSONAL_TEXT =", value, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextNotEqualTo(String value) {
			addCriterion("PERSONAL_TEXT <>", value, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextGreaterThan(String value) {
			addCriterion("PERSONAL_TEXT >", value, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextGreaterThanOrEqualTo(String value) {
			addCriterion("PERSONAL_TEXT >=", value, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextLessThan(String value) {
			addCriterion("PERSONAL_TEXT <", value, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextLessThanOrEqualTo(String value) {
			addCriterion("PERSONAL_TEXT <=", value, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextLike(String value) {
			addCriterion("PERSONAL_TEXT like", value, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextNotLike(String value) {
			addCriterion("PERSONAL_TEXT not like", value, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextIn(List<String> values) {
			addCriterion("PERSONAL_TEXT in", values, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextNotIn(List<String> values) {
			addCriterion("PERSONAL_TEXT not in", values, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextBetween(String value1, String value2) {
			addCriterion("PERSONAL_TEXT between", value1, value2, "personalText");
			return (Criteria) this;
		}

		public Criteria andPersonalTextNotBetween(String value1, String value2) {
			addCriterion("PERSONAL_TEXT not between", value1, value2, "personalText");
			return (Criteria) this;
		}

		public Criteria andGenderIdIsNull() {
			addCriterion("GENDER_ID is null");
			return (Criteria) this;
		}

		public Criteria andGenderIdIsNotNull() {
			addCriterion("GENDER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andGenderIdEqualTo(Integer value) {
			addCriterion("GENDER_ID =", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdNotEqualTo(Integer value) {
			addCriterion("GENDER_ID <>", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdGreaterThan(Integer value) {
			addCriterion("GENDER_ID >", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("GENDER_ID >=", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdLessThan(Integer value) {
			addCriterion("GENDER_ID <", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdLessThanOrEqualTo(Integer value) {
			addCriterion("GENDER_ID <=", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdIn(List<Integer> values) {
			addCriterion("GENDER_ID in", values, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdNotIn(List<Integer> values) {
			addCriterion("GENDER_ID not in", values, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdBetween(Integer value1, Integer value2) {
			addCriterion("GENDER_ID between", value1, value2, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdNotBetween(Integer value1, Integer value2) {
			addCriterion("GENDER_ID not between", value1, value2, "genderId");
			return (Criteria) this;
		}

		public Criteria andBirthDateIsNull() {
			addCriterion("BIRTH_DATE is null");
			return (Criteria) this;
		}

		public Criteria andBirthDateIsNotNull() {
			addCriterion("BIRTH_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andBirthDateEqualTo(Date value) {
			addCriterion("BIRTH_DATE =", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateNotEqualTo(Date value) {
			addCriterion("BIRTH_DATE <>", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateGreaterThan(Date value) {
			addCriterion("BIRTH_DATE >", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateGreaterThanOrEqualTo(Date value) {
			addCriterion("BIRTH_DATE >=", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateLessThan(Date value) {
			addCriterion("BIRTH_DATE <", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateLessThanOrEqualTo(Date value) {
			addCriterion("BIRTH_DATE <=", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateIn(List<Date> values) {
			addCriterion("BIRTH_DATE in", values, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateNotIn(List<Date> values) {
			addCriterion("BIRTH_DATE not in", values, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateBetween(Date value1, Date value2) {
			addCriterion("BIRTH_DATE between", value1, value2, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateNotBetween(Date value1, Date value2) {
			addCriterion("BIRTH_DATE not between", value1, value2, "birthDate");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleIsNull() {
			addCriterion("WEBSITE_TITLE is null");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleIsNotNull() {
			addCriterion("WEBSITE_TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleEqualTo(String value) {
			addCriterion("WEBSITE_TITLE =", value, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleNotEqualTo(String value) {
			addCriterion("WEBSITE_TITLE <>", value, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleGreaterThan(String value) {
			addCriterion("WEBSITE_TITLE >", value, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleGreaterThanOrEqualTo(String value) {
			addCriterion("WEBSITE_TITLE >=", value, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleLessThan(String value) {
			addCriterion("WEBSITE_TITLE <", value, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleLessThanOrEqualTo(String value) {
			addCriterion("WEBSITE_TITLE <=", value, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleLike(String value) {
			addCriterion("WEBSITE_TITLE like", value, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleNotLike(String value) {
			addCriterion("WEBSITE_TITLE not like", value, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleIn(List<String> values) {
			addCriterion("WEBSITE_TITLE in", values, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleNotIn(List<String> values) {
			addCriterion("WEBSITE_TITLE not in", values, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleBetween(String value1, String value2) {
			addCriterion("WEBSITE_TITLE between", value1, value2, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteTitleNotBetween(String value1, String value2) {
			addCriterion("WEBSITE_TITLE not between", value1, value2, "websiteTitle");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlIsNull() {
			addCriterion("WEBSITE_URL is null");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlIsNotNull() {
			addCriterion("WEBSITE_URL is not null");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlEqualTo(String value) {
			addCriterion("WEBSITE_URL =", value, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlNotEqualTo(String value) {
			addCriterion("WEBSITE_URL <>", value, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlGreaterThan(String value) {
			addCriterion("WEBSITE_URL >", value, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlGreaterThanOrEqualTo(String value) {
			addCriterion("WEBSITE_URL >=", value, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlLessThan(String value) {
			addCriterion("WEBSITE_URL <", value, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlLessThanOrEqualTo(String value) {
			addCriterion("WEBSITE_URL <=", value, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlLike(String value) {
			addCriterion("WEBSITE_URL like", value, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlNotLike(String value) {
			addCriterion("WEBSITE_URL not like", value, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlIn(List<String> values) {
			addCriterion("WEBSITE_URL in", values, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlNotIn(List<String> values) {
			addCriterion("WEBSITE_URL not in", values, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlBetween(String value1, String value2) {
			addCriterion("WEBSITE_URL between", value1, value2, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andWebsiteUrlNotBetween(String value1, String value2) {
			addCriterion("WEBSITE_URL not between", value1, value2, "websiteUrl");
			return (Criteria) this;
		}

		public Criteria andLocationIsNull() {
			addCriterion("LOCATION is null");
			return (Criteria) this;
		}

		public Criteria andLocationIsNotNull() {
			addCriterion("LOCATION is not null");
			return (Criteria) this;
		}

		public Criteria andLocationEqualTo(String value) {
			addCriterion("LOCATION =", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotEqualTo(String value) {
			addCriterion("LOCATION <>", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationGreaterThan(String value) {
			addCriterion("LOCATION >", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationGreaterThanOrEqualTo(String value) {
			addCriterion("LOCATION >=", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationLessThan(String value) {
			addCriterion("LOCATION <", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationLessThanOrEqualTo(String value) {
			addCriterion("LOCATION <=", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationLike(String value) {
			addCriterion("LOCATION like", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotLike(String value) {
			addCriterion("LOCATION not like", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationIn(List<String> values) {
			addCriterion("LOCATION in", values, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotIn(List<String> values) {
			addCriterion("LOCATION not in", values, "location");
			return (Criteria) this;
		}

		public Criteria andLocationBetween(String value1, String value2) {
			addCriterion("LOCATION between", value1, value2, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotBetween(String value1, String value2) {
			addCriterion("LOCATION not between", value1, value2, "location");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagIsNull() {
			addCriterion("SHOW_ONLINE_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagIsNotNull() {
			addCriterion("SHOW_ONLINE_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagEqualTo(Boolean value) {
			addCriterion("SHOW_ONLINE_FLAG =", value, "showOnlineFlag");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagNotEqualTo(Boolean value) {
			addCriterion("SHOW_ONLINE_FLAG <>", value, "showOnlineFlag");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagGreaterThan(Boolean value) {
			addCriterion("SHOW_ONLINE_FLAG >", value, "showOnlineFlag");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagGreaterThanOrEqualTo(Boolean value) {
			addCriterion("SHOW_ONLINE_FLAG >=", value, "showOnlineFlag");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagLessThan(Boolean value) {
			addCriterion("SHOW_ONLINE_FLAG <", value, "showOnlineFlag");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagLessThanOrEqualTo(Boolean value) {
			addCriterion("SHOW_ONLINE_FLAG <=", value, "showOnlineFlag");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagIn(List<Boolean> values) {
			addCriterion("SHOW_ONLINE_FLAG in", values, "showOnlineFlag");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagNotIn(List<Boolean> values) {
			addCriterion("SHOW_ONLINE_FLAG not in", values, "showOnlineFlag");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagBetween(Boolean value1, Boolean value2) {
			addCriterion("SHOW_ONLINE_FLAG between", value1, value2, "showOnlineFlag");
			return (Criteria) this;
		}

		public Criteria andShowOnlineFlagNotBetween(Boolean value1, Boolean value2) {
			addCriterion("SHOW_ONLINE_FLAG not between", value1, value2, "showOnlineFlag");
			return (Criteria) this;
		}

		public Criteria andTimeFormatIsNull() {
			addCriterion("TIME_FORMAT is null");
			return (Criteria) this;
		}

		public Criteria andTimeFormatIsNotNull() {
			addCriterion("TIME_FORMAT is not null");
			return (Criteria) this;
		}

		public Criteria andTimeFormatEqualTo(String value) {
			addCriterion("TIME_FORMAT =", value, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatNotEqualTo(String value) {
			addCriterion("TIME_FORMAT <>", value, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatGreaterThan(String value) {
			addCriterion("TIME_FORMAT >", value, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatGreaterThanOrEqualTo(String value) {
			addCriterion("TIME_FORMAT >=", value, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatLessThan(String value) {
			addCriterion("TIME_FORMAT <", value, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatLessThanOrEqualTo(String value) {
			addCriterion("TIME_FORMAT <=", value, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatLike(String value) {
			addCriterion("TIME_FORMAT like", value, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatNotLike(String value) {
			addCriterion("TIME_FORMAT not like", value, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatIn(List<String> values) {
			addCriterion("TIME_FORMAT in", values, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatNotIn(List<String> values) {
			addCriterion("TIME_FORMAT not in", values, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatBetween(String value1, String value2) {
			addCriterion("TIME_FORMAT between", value1, value2, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andTimeFormatNotBetween(String value1, String value2) {
			addCriterion("TIME_FORMAT not between", value1, value2, "timeFormat");
			return (Criteria) this;
		}

		public Criteria andSignatureIsNull() {
			addCriterion("SIGNATURE is null");
			return (Criteria) this;
		}

		public Criteria andSignatureIsNotNull() {
			addCriterion("SIGNATURE is not null");
			return (Criteria) this;
		}

		public Criteria andSignatureEqualTo(String value) {
			addCriterion("SIGNATURE =", value, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureNotEqualTo(String value) {
			addCriterion("SIGNATURE <>", value, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureGreaterThan(String value) {
			addCriterion("SIGNATURE >", value, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureGreaterThanOrEqualTo(String value) {
			addCriterion("SIGNATURE >=", value, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureLessThan(String value) {
			addCriterion("SIGNATURE <", value, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureLessThanOrEqualTo(String value) {
			addCriterion("SIGNATURE <=", value, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureLike(String value) {
			addCriterion("SIGNATURE like", value, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureNotLike(String value) {
			addCriterion("SIGNATURE not like", value, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureIn(List<String> values) {
			addCriterion("SIGNATURE in", values, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureNotIn(List<String> values) {
			addCriterion("SIGNATURE not in", values, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureBetween(String value1, String value2) {
			addCriterion("SIGNATURE between", value1, value2, "signature");
			return (Criteria) this;
		}

		public Criteria andSignatureNotBetween(String value1, String value2) {
			addCriterion("SIGNATURE not between", value1, value2, "signature");
			return (Criteria) this;
		}

		public Criteria andActiveFlagIsNull() {
			addCriterion("ACTIVE_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andActiveFlagIsNotNull() {
			addCriterion("ACTIVE_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andActiveFlagEqualTo(Boolean value) {
			addCriterion("ACTIVE_FLAG =", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagNotEqualTo(Boolean value) {
			addCriterion("ACTIVE_FLAG <>", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagGreaterThan(Boolean value) {
			addCriterion("ACTIVE_FLAG >", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagGreaterThanOrEqualTo(Boolean value) {
			addCriterion("ACTIVE_FLAG >=", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagLessThan(Boolean value) {
			addCriterion("ACTIVE_FLAG <", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagLessThanOrEqualTo(Boolean value) {
			addCriterion("ACTIVE_FLAG <=", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagIn(List<Boolean> values) {
			addCriterion("ACTIVE_FLAG in", values, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagNotIn(List<Boolean> values) {
			addCriterion("ACTIVE_FLAG not in", values, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagBetween(Boolean value1, Boolean value2) {
			addCriterion("ACTIVE_FLAG between", value1, value2, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagNotBetween(Boolean value1, Boolean value2) {
			addCriterion("ACTIVE_FLAG not between", value1, value2, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetIsNull() {
			addCriterion("TIME_OFFSET is null");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetIsNotNull() {
			addCriterion("TIME_OFFSET is not null");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetEqualTo(Short value) {
			addCriterion("TIME_OFFSET =", value, "timeOffset");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetNotEqualTo(Short value) {
			addCriterion("TIME_OFFSET <>", value, "timeOffset");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetGreaterThan(Short value) {
			addCriterion("TIME_OFFSET >", value, "timeOffset");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetGreaterThanOrEqualTo(Short value) {
			addCriterion("TIME_OFFSET >=", value, "timeOffset");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetLessThan(Short value) {
			addCriterion("TIME_OFFSET <", value, "timeOffset");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetLessThanOrEqualTo(Short value) {
			addCriterion("TIME_OFFSET <=", value, "timeOffset");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetIn(List<Short> values) {
			addCriterion("TIME_OFFSET in", values, "timeOffset");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetNotIn(List<Short> values) {
			addCriterion("TIME_OFFSET not in", values, "timeOffset");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetBetween(Short value1, Short value2) {
			addCriterion("TIME_OFFSET between", value1, value2, "timeOffset");
			return (Criteria) this;
		}

		public Criteria andTimeOffsetNotBetween(Short value1, Short value2) {
			addCriterion("TIME_OFFSET not between", value1, value2, "timeOffset");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagIsNull() {
			addCriterion("PM_EMAIL_NOTIF_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagIsNotNull() {
			addCriterion("PM_EMAIL_NOTIF_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagEqualTo(Boolean value) {
			addCriterion("PM_EMAIL_NOTIF_FLAG =", value, "pmEmailNotifFlag");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagNotEqualTo(Boolean value) {
			addCriterion("PM_EMAIL_NOTIF_FLAG <>", value, "pmEmailNotifFlag");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagGreaterThan(Boolean value) {
			addCriterion("PM_EMAIL_NOTIF_FLAG >", value, "pmEmailNotifFlag");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagGreaterThanOrEqualTo(Boolean value) {
			addCriterion("PM_EMAIL_NOTIF_FLAG >=", value, "pmEmailNotifFlag");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagLessThan(Boolean value) {
			addCriterion("PM_EMAIL_NOTIF_FLAG <", value, "pmEmailNotifFlag");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagLessThanOrEqualTo(Boolean value) {
			addCriterion("PM_EMAIL_NOTIF_FLAG <=", value, "pmEmailNotifFlag");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagIn(List<Boolean> values) {
			addCriterion("PM_EMAIL_NOTIF_FLAG in", values, "pmEmailNotifFlag");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagNotIn(List<Boolean> values) {
			addCriterion("PM_EMAIL_NOTIF_FLAG not in", values, "pmEmailNotifFlag");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagBetween(Boolean value1, Boolean value2) {
			addCriterion("PM_EMAIL_NOTIF_FLAG between", value1, value2, "pmEmailNotifFlag");
			return (Criteria) this;
		}

		public Criteria andPmEmailNotifFlagNotBetween(Boolean value1, Boolean value2) {
			addCriterion("PM_EMAIL_NOTIF_FLAG not between", value1, value2, "pmEmailNotifFlag");
			return (Criteria) this;
		}

		public Criteria andAvatarIdIsNull() {
			addCriterion("AVATAR_ID is null");
			return (Criteria) this;
		}

		public Criteria andAvatarIdIsNotNull() {
			addCriterion("AVATAR_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAvatarIdEqualTo(Integer value) {
			addCriterion("AVATAR_ID =", value, "avatarId");
			return (Criteria) this;
		}

		public Criteria andAvatarIdNotEqualTo(Integer value) {
			addCriterion("AVATAR_ID <>", value, "avatarId");
			return (Criteria) this;
		}

		public Criteria andAvatarIdGreaterThan(Integer value) {
			addCriterion("AVATAR_ID >", value, "avatarId");
			return (Criteria) this;
		}

		public Criteria andAvatarIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("AVATAR_ID >=", value, "avatarId");
			return (Criteria) this;
		}

		public Criteria andAvatarIdLessThan(Integer value) {
			addCriterion("AVATAR_ID <", value, "avatarId");
			return (Criteria) this;
		}

		public Criteria andAvatarIdLessThanOrEqualTo(Integer value) {
			addCriterion("AVATAR_ID <=", value, "avatarId");
			return (Criteria) this;
		}

		public Criteria andAvatarIdIn(List<Integer> values) {
			addCriterion("AVATAR_ID in", values, "avatarId");
			return (Criteria) this;
		}

		public Criteria andAvatarIdNotIn(List<Integer> values) {
			addCriterion("AVATAR_ID not in", values, "avatarId");
			return (Criteria) this;
		}

		public Criteria andAvatarIdBetween(Integer value1, Integer value2) {
			addCriterion("AVATAR_ID between", value1, value2, "avatarId");
			return (Criteria) this;
		}

		public Criteria andAvatarIdNotBetween(Integer value1, Integer value2) {
			addCriterion("AVATAR_ID not between", value1, value2, "avatarId");
			return (Criteria) this;
		}

		public Criteria andUserTitleIsNull() {
			addCriterion("USER_TITLE is null");
			return (Criteria) this;
		}

		public Criteria andUserTitleIsNotNull() {
			addCriterion("USER_TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andUserTitleEqualTo(String value) {
			addCriterion("USER_TITLE =", value, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleNotEqualTo(String value) {
			addCriterion("USER_TITLE <>", value, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleGreaterThan(String value) {
			addCriterion("USER_TITLE >", value, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleGreaterThanOrEqualTo(String value) {
			addCriterion("USER_TITLE >=", value, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleLessThan(String value) {
			addCriterion("USER_TITLE <", value, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleLessThanOrEqualTo(String value) {
			addCriterion("USER_TITLE <=", value, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleLike(String value) {
			addCriterion("USER_TITLE like", value, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleNotLike(String value) {
			addCriterion("USER_TITLE not like", value, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleIn(List<String> values) {
			addCriterion("USER_TITLE in", values, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleNotIn(List<String> values) {
			addCriterion("USER_TITLE not in", values, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleBetween(String value1, String value2) {
			addCriterion("USER_TITLE between", value1, value2, "userTitle");
			return (Criteria) this;
		}

		public Criteria andUserTitleNotBetween(String value1, String value2) {
			addCriterion("USER_TITLE not between", value1, value2, "userTitle");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInIsNull() {
			addCriterion("TOTAL_TIME_LOGGED_IN is null");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInIsNotNull() {
			addCriterion("TOTAL_TIME_LOGGED_IN is not null");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInEqualTo(Integer value) {
			addCriterion("TOTAL_TIME_LOGGED_IN =", value, "totalTimeLoggedIn");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInNotEqualTo(Integer value) {
			addCriterion("TOTAL_TIME_LOGGED_IN <>", value, "totalTimeLoggedIn");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInGreaterThan(Integer value) {
			addCriterion("TOTAL_TIME_LOGGED_IN >", value, "totalTimeLoggedIn");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInGreaterThanOrEqualTo(Integer value) {
			addCriterion("TOTAL_TIME_LOGGED_IN >=", value, "totalTimeLoggedIn");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInLessThan(Integer value) {
			addCriterion("TOTAL_TIME_LOGGED_IN <", value, "totalTimeLoggedIn");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInLessThanOrEqualTo(Integer value) {
			addCriterion("TOTAL_TIME_LOGGED_IN <=", value, "totalTimeLoggedIn");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInIn(List<Integer> values) {
			addCriterion("TOTAL_TIME_LOGGED_IN in", values, "totalTimeLoggedIn");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInNotIn(List<Integer> values) {
			addCriterion("TOTAL_TIME_LOGGED_IN not in", values, "totalTimeLoggedIn");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInBetween(Integer value1, Integer value2) {
			addCriterion("TOTAL_TIME_LOGGED_IN between", value1, value2, "totalTimeLoggedIn");
			return (Criteria) this;
		}

		public Criteria andTotalTimeLoggedInNotBetween(Integer value1, Integer value2) {
			addCriterion("TOTAL_TIME_LOGGED_IN not between", value1, value2, "totalTimeLoggedIn");
			return (Criteria) this;
		}

		public Criteria andWarnLevelIsNull() {
			addCriterion("WARN_LEVEL is null");
			return (Criteria) this;
		}

		public Criteria andWarnLevelIsNotNull() {
			addCriterion("WARN_LEVEL is not null");
			return (Criteria) this;
		}

		public Criteria andWarnLevelEqualTo(Byte value) {
			addCriterion("WARN_LEVEL =", value, "warnLevel");
			return (Criteria) this;
		}

		public Criteria andWarnLevelNotEqualTo(Byte value) {
			addCriterion("WARN_LEVEL <>", value, "warnLevel");
			return (Criteria) this;
		}

		public Criteria andWarnLevelGreaterThan(Byte value) {
			addCriterion("WARN_LEVEL >", value, "warnLevel");
			return (Criteria) this;
		}

		public Criteria andWarnLevelGreaterThanOrEqualTo(Byte value) {
			addCriterion("WARN_LEVEL >=", value, "warnLevel");
			return (Criteria) this;
		}

		public Criteria andWarnLevelLessThan(Byte value) {
			addCriterion("WARN_LEVEL <", value, "warnLevel");
			return (Criteria) this;
		}

		public Criteria andWarnLevelLessThanOrEqualTo(Byte value) {
			addCriterion("WARN_LEVEL <=", value, "warnLevel");
			return (Criteria) this;
		}

		public Criteria andWarnLevelIn(List<Byte> values) {
			addCriterion("WARN_LEVEL in", values, "warnLevel");
			return (Criteria) this;
		}

		public Criteria andWarnLevelNotIn(List<Byte> values) {
			addCriterion("WARN_LEVEL not in", values, "warnLevel");
			return (Criteria) this;
		}

		public Criteria andWarnLevelBetween(Byte value1, Byte value2) {
			addCriterion("WARN_LEVEL between", value1, value2, "warnLevel");
			return (Criteria) this;
		}

		public Criteria andWarnLevelNotBetween(Byte value1, Byte value2) {
			addCriterion("WARN_LEVEL not between", value1, value2, "warnLevel");
			return (Criteria) this;
		}

		public Criteria andLockedUntilIsNull() {
			addCriterion("LOCKED_UNTIL is null");
			return (Criteria) this;
		}

		public Criteria andLockedUntilIsNotNull() {
			addCriterion("LOCKED_UNTIL is not null");
			return (Criteria) this;
		}

		public Criteria andLockedUntilEqualTo(Date value) {
			addCriterion("LOCKED_UNTIL =", value, "lockedUntil");
			return (Criteria) this;
		}

		public Criteria andLockedUntilNotEqualTo(Date value) {
			addCriterion("LOCKED_UNTIL <>", value, "lockedUntil");
			return (Criteria) this;
		}

		public Criteria andLockedUntilGreaterThan(Date value) {
			addCriterion("LOCKED_UNTIL >", value, "lockedUntil");
			return (Criteria) this;
		}

		public Criteria andLockedUntilGreaterThanOrEqualTo(Date value) {
			addCriterion("LOCKED_UNTIL >=", value, "lockedUntil");
			return (Criteria) this;
		}

		public Criteria andLockedUntilLessThan(Date value) {
			addCriterion("LOCKED_UNTIL <", value, "lockedUntil");
			return (Criteria) this;
		}

		public Criteria andLockedUntilLessThanOrEqualTo(Date value) {
			addCriterion("LOCKED_UNTIL <=", value, "lockedUntil");
			return (Criteria) this;
		}

		public Criteria andLockedUntilIn(List<Date> values) {
			addCriterion("LOCKED_UNTIL in", values, "lockedUntil");
			return (Criteria) this;
		}

		public Criteria andLockedUntilNotIn(List<Date> values) {
			addCriterion("LOCKED_UNTIL not in", values, "lockedUntil");
			return (Criteria) this;
		}

		public Criteria andLockedUntilBetween(Date value1, Date value2) {
			addCriterion("LOCKED_UNTIL between", value1, value2, "lockedUntil");
			return (Criteria) this;
		}

		public Criteria andLockedUntilNotBetween(Date value1, Date value2) {
			addCriterion("LOCKED_UNTIL not between", value1, value2, "lockedUntil");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsIsNull() {
			addCriterion("LOGIN_FAILED_ATTEMPTS is null");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsIsNotNull() {
			addCriterion("LOGIN_FAILED_ATTEMPTS is not null");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsEqualTo(Byte value) {
			addCriterion("LOGIN_FAILED_ATTEMPTS =", value, "loginFailedAttempts");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsNotEqualTo(Byte value) {
			addCriterion("LOGIN_FAILED_ATTEMPTS <>", value, "loginFailedAttempts");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsGreaterThan(Byte value) {
			addCriterion("LOGIN_FAILED_ATTEMPTS >", value, "loginFailedAttempts");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsGreaterThanOrEqualTo(Byte value) {
			addCriterion("LOGIN_FAILED_ATTEMPTS >=", value, "loginFailedAttempts");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsLessThan(Byte value) {
			addCriterion("LOGIN_FAILED_ATTEMPTS <", value, "loginFailedAttempts");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsLessThanOrEqualTo(Byte value) {
			addCriterion("LOGIN_FAILED_ATTEMPTS <=", value, "loginFailedAttempts");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsIn(List<Byte> values) {
			addCriterion("LOGIN_FAILED_ATTEMPTS in", values, "loginFailedAttempts");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsNotIn(List<Byte> values) {
			addCriterion("LOGIN_FAILED_ATTEMPTS not in", values, "loginFailedAttempts");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsBetween(Byte value1, Byte value2) {
			addCriterion("LOGIN_FAILED_ATTEMPTS between", value1, value2, "loginFailedAttempts");
			return (Criteria) this;
		}

		public Criteria andLoginFailedAttemptsNotBetween(Byte value1, Byte value2) {
			addCriterion("LOGIN_FAILED_ATTEMPTS not between", value1, value2, "loginFailedAttempts");
			return (Criteria) this;
		}

		public Criteria andCustomTitleIsNull() {
			addCriterion("CUSTOM_TITLE is null");
			return (Criteria) this;
		}

		public Criteria andCustomTitleIsNotNull() {
			addCriterion("CUSTOM_TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andCustomTitleEqualTo(String value) {
			addCriterion("CUSTOM_TITLE =", value, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleNotEqualTo(String value) {
			addCriterion("CUSTOM_TITLE <>", value, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleGreaterThan(String value) {
			addCriterion("CUSTOM_TITLE >", value, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleGreaterThanOrEqualTo(String value) {
			addCriterion("CUSTOM_TITLE >=", value, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleLessThan(String value) {
			addCriterion("CUSTOM_TITLE <", value, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleLessThanOrEqualTo(String value) {
			addCriterion("CUSTOM_TITLE <=", value, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleLike(String value) {
			addCriterion("CUSTOM_TITLE like", value, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleNotLike(String value) {
			addCriterion("CUSTOM_TITLE not like", value, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleIn(List<String> values) {
			addCriterion("CUSTOM_TITLE in", values, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleNotIn(List<String> values) {
			addCriterion("CUSTOM_TITLE not in", values, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleBetween(String value1, String value2) {
			addCriterion("CUSTOM_TITLE between", value1, value2, "customTitle");
			return (Criteria) this;
		}

		public Criteria andCustomTitleNotBetween(String value1, String value2) {
			addCriterion("CUSTOM_TITLE not between", value1, value2, "customTitle");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsIsNull() {
			addCriterion("ACTIVE_CONNECTIONS is null");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsIsNotNull() {
			addCriterion("ACTIVE_CONNECTIONS is not null");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsEqualTo(Integer value) {
			addCriterion("ACTIVE_CONNECTIONS =", value, "activeConnections");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsNotEqualTo(Integer value) {
			addCriterion("ACTIVE_CONNECTIONS <>", value, "activeConnections");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsGreaterThan(Integer value) {
			addCriterion("ACTIVE_CONNECTIONS >", value, "activeConnections");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsGreaterThanOrEqualTo(Integer value) {
			addCriterion("ACTIVE_CONNECTIONS >=", value, "activeConnections");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsLessThan(Integer value) {
			addCriterion("ACTIVE_CONNECTIONS <", value, "activeConnections");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsLessThanOrEqualTo(Integer value) {
			addCriterion("ACTIVE_CONNECTIONS <=", value, "activeConnections");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsIn(List<Integer> values) {
			addCriterion("ACTIVE_CONNECTIONS in", values, "activeConnections");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsNotIn(List<Integer> values) {
			addCriterion("ACTIVE_CONNECTIONS not in", values, "activeConnections");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsBetween(Integer value1, Integer value2) {
			addCriterion("ACTIVE_CONNECTIONS between", value1, value2, "activeConnections");
			return (Criteria) this;
		}

		public Criteria andActiveConnectionsNotBetween(Integer value1, Integer value2) {
			addCriterion("ACTIVE_CONNECTIONS not between", value1, value2, "activeConnections");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeIsNull() {
			addCriterion("EMAIL_ACTIVATION_CODE is null");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeIsNotNull() {
			addCriterion("EMAIL_ACTIVATION_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeEqualTo(String value) {
			addCriterion("EMAIL_ACTIVATION_CODE =", value, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeNotEqualTo(String value) {
			addCriterion("EMAIL_ACTIVATION_CODE <>", value, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeGreaterThan(String value) {
			addCriterion("EMAIL_ACTIVATION_CODE >", value, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL_ACTIVATION_CODE >=", value, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeLessThan(String value) {
			addCriterion("EMAIL_ACTIVATION_CODE <", value, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeLessThanOrEqualTo(String value) {
			addCriterion("EMAIL_ACTIVATION_CODE <=", value, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeLike(String value) {
			addCriterion("EMAIL_ACTIVATION_CODE like", value, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeNotLike(String value) {
			addCriterion("EMAIL_ACTIVATION_CODE not like", value, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeIn(List<String> values) {
			addCriterion("EMAIL_ACTIVATION_CODE in", values, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeNotIn(List<String> values) {
			addCriterion("EMAIL_ACTIVATION_CODE not in", values, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeBetween(String value1, String value2) {
			addCriterion("EMAIL_ACTIVATION_CODE between", value1, value2, "emailActivationCode");
			return (Criteria) this;
		}

		public Criteria andEmailActivationCodeNotBetween(String value1, String value2) {
			addCriterion("EMAIL_ACTIVATION_CODE not between", value1, value2, "emailActivationCode");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users
	 * @mbg.generated  Sun Feb 17 11:54:00 EST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbggenerated do_not_delete_during_merge Sun Nov 13 00:35:22 EST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}