package com.zfgc.dbobj;

import java.util.Date;

public class UserProfileViewDbObj {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.USERS_ID
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private Integer usersId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.LOGIN_NAME
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.DISPLAY_NAME
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String displayName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.PRIMARY_IP
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String primaryIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.PRIMARY_MEMBER_GROUP_ID
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private Integer primaryMemberGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.DATE_REGISTERED
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private Date dateRegistered;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.EMAIL_ADDRESS
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String emailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.LAST_LOGIN
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private Date lastLogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.PERSONAL_TEXT
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String personalText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.GENDER
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.BIRTH_DATE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private Date birthDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.USER_TITLE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String userTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.HIDE_EMAIL_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private Boolean hideEmailFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.HIDE_AGE_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private Boolean hideAgeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.HIDE_GENDER_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private Boolean hideGenderFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.HIDE_BIRTH_DATE_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private Boolean hideBirthDateFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.TIME_OFFSET
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private Short timeOffset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.AVATAR_FILENAME
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String avatarFilename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.TIME_ZONE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String timeZone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.SKYPE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String skype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.AIM
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String aim;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.YIM
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String yim;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.GTALK
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String gtalk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.STEAM
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String steam;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.NNID
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String nnid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.XBOX_LIVE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String xboxLive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_PROFILE_VIEW.PSN
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	private String psn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.USERS_ID
	 * @return  the value of USER_PROFILE_VIEW.USERS_ID
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public Integer getUsersId() {
		return usersId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.USERS_ID
	 * @param usersId  the value for USER_PROFILE_VIEW.USERS_ID
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setUsersId(Integer usersId) {
		this.usersId = usersId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.LOGIN_NAME
	 * @return  the value of USER_PROFILE_VIEW.LOGIN_NAME
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.LOGIN_NAME
	 * @param loginName  the value for USER_PROFILE_VIEW.LOGIN_NAME
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.DISPLAY_NAME
	 * @return  the value of USER_PROFILE_VIEW.DISPLAY_NAME
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getDisplayName() {
		return displayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.DISPLAY_NAME
	 * @param displayName  the value for USER_PROFILE_VIEW.DISPLAY_NAME
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.PRIMARY_IP
	 * @return  the value of USER_PROFILE_VIEW.PRIMARY_IP
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getPrimaryIp() {
		return primaryIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.PRIMARY_IP
	 * @param primaryIp  the value for USER_PROFILE_VIEW.PRIMARY_IP
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setPrimaryIp(String primaryIp) {
		this.primaryIp = primaryIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.PRIMARY_MEMBER_GROUP_ID
	 * @return  the value of USER_PROFILE_VIEW.PRIMARY_MEMBER_GROUP_ID
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public Integer getPrimaryMemberGroupId() {
		return primaryMemberGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.PRIMARY_MEMBER_GROUP_ID
	 * @param primaryMemberGroupId  the value for USER_PROFILE_VIEW.PRIMARY_MEMBER_GROUP_ID
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setPrimaryMemberGroupId(Integer primaryMemberGroupId) {
		this.primaryMemberGroupId = primaryMemberGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.DATE_REGISTERED
	 * @return  the value of USER_PROFILE_VIEW.DATE_REGISTERED
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public Date getDateRegistered() {
		return dateRegistered;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.DATE_REGISTERED
	 * @param dateRegistered  the value for USER_PROFILE_VIEW.DATE_REGISTERED
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setDateRegistered(Date dateRegistered) {
		this.dateRegistered = dateRegistered;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.EMAIL_ADDRESS
	 * @return  the value of USER_PROFILE_VIEW.EMAIL_ADDRESS
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getEmailAddress() {
		return emailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.EMAIL_ADDRESS
	 * @param emailAddress  the value for USER_PROFILE_VIEW.EMAIL_ADDRESS
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.LAST_LOGIN
	 * @return  the value of USER_PROFILE_VIEW.LAST_LOGIN
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public Date getLastLogin() {
		return lastLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.LAST_LOGIN
	 * @param lastLogin  the value for USER_PROFILE_VIEW.LAST_LOGIN
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.PERSONAL_TEXT
	 * @return  the value of USER_PROFILE_VIEW.PERSONAL_TEXT
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getPersonalText() {
		return personalText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.PERSONAL_TEXT
	 * @param personalText  the value for USER_PROFILE_VIEW.PERSONAL_TEXT
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setPersonalText(String personalText) {
		this.personalText = personalText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.GENDER
	 * @return  the value of USER_PROFILE_VIEW.GENDER
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.GENDER
	 * @param gender  the value for USER_PROFILE_VIEW.GENDER
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.BIRTH_DATE
	 * @return  the value of USER_PROFILE_VIEW.BIRTH_DATE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public Date getBirthDate() {
		return birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.BIRTH_DATE
	 * @param birthDate  the value for USER_PROFILE_VIEW.BIRTH_DATE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.USER_TITLE
	 * @return  the value of USER_PROFILE_VIEW.USER_TITLE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getUserTitle() {
		return userTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.USER_TITLE
	 * @param userTitle  the value for USER_PROFILE_VIEW.USER_TITLE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setUserTitle(String userTitle) {
		this.userTitle = userTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.HIDE_EMAIL_FLAG
	 * @return  the value of USER_PROFILE_VIEW.HIDE_EMAIL_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public Boolean getHideEmailFlag() {
		return hideEmailFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.HIDE_EMAIL_FLAG
	 * @param hideEmailFlag  the value for USER_PROFILE_VIEW.HIDE_EMAIL_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setHideEmailFlag(Boolean hideEmailFlag) {
		this.hideEmailFlag = hideEmailFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.HIDE_AGE_FLAG
	 * @return  the value of USER_PROFILE_VIEW.HIDE_AGE_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public Boolean getHideAgeFlag() {
		return hideAgeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.HIDE_AGE_FLAG
	 * @param hideAgeFlag  the value for USER_PROFILE_VIEW.HIDE_AGE_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setHideAgeFlag(Boolean hideAgeFlag) {
		this.hideAgeFlag = hideAgeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.HIDE_GENDER_FLAG
	 * @return  the value of USER_PROFILE_VIEW.HIDE_GENDER_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public Boolean getHideGenderFlag() {
		return hideGenderFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.HIDE_GENDER_FLAG
	 * @param hideGenderFlag  the value for USER_PROFILE_VIEW.HIDE_GENDER_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setHideGenderFlag(Boolean hideGenderFlag) {
		this.hideGenderFlag = hideGenderFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.HIDE_BIRTH_DATE_FLAG
	 * @return  the value of USER_PROFILE_VIEW.HIDE_BIRTH_DATE_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public Boolean getHideBirthDateFlag() {
		return hideBirthDateFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.HIDE_BIRTH_DATE_FLAG
	 * @param hideBirthDateFlag  the value for USER_PROFILE_VIEW.HIDE_BIRTH_DATE_FLAG
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setHideBirthDateFlag(Boolean hideBirthDateFlag) {
		this.hideBirthDateFlag = hideBirthDateFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.TIME_OFFSET
	 * @return  the value of USER_PROFILE_VIEW.TIME_OFFSET
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public Short getTimeOffset() {
		return timeOffset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.TIME_OFFSET
	 * @param timeOffset  the value for USER_PROFILE_VIEW.TIME_OFFSET
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setTimeOffset(Short timeOffset) {
		this.timeOffset = timeOffset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.AVATAR_FILENAME
	 * @return  the value of USER_PROFILE_VIEW.AVATAR_FILENAME
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getAvatarFilename() {
		return avatarFilename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.AVATAR_FILENAME
	 * @param avatarFilename  the value for USER_PROFILE_VIEW.AVATAR_FILENAME
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setAvatarFilename(String avatarFilename) {
		this.avatarFilename = avatarFilename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.TIME_ZONE
	 * @return  the value of USER_PROFILE_VIEW.TIME_ZONE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getTimeZone() {
		return timeZone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.TIME_ZONE
	 * @param timeZone  the value for USER_PROFILE_VIEW.TIME_ZONE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.SKYPE
	 * @return  the value of USER_PROFILE_VIEW.SKYPE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getSkype() {
		return skype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.SKYPE
	 * @param skype  the value for USER_PROFILE_VIEW.SKYPE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setSkype(String skype) {
		this.skype = skype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.AIM
	 * @return  the value of USER_PROFILE_VIEW.AIM
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getAim() {
		return aim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.AIM
	 * @param aim  the value for USER_PROFILE_VIEW.AIM
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setAim(String aim) {
		this.aim = aim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.YIM
	 * @return  the value of USER_PROFILE_VIEW.YIM
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getYim() {
		return yim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.YIM
	 * @param yim  the value for USER_PROFILE_VIEW.YIM
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setYim(String yim) {
		this.yim = yim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.GTALK
	 * @return  the value of USER_PROFILE_VIEW.GTALK
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getGtalk() {
		return gtalk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.GTALK
	 * @param gtalk  the value for USER_PROFILE_VIEW.GTALK
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setGtalk(String gtalk) {
		this.gtalk = gtalk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.STEAM
	 * @return  the value of USER_PROFILE_VIEW.STEAM
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getSteam() {
		return steam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.STEAM
	 * @param steam  the value for USER_PROFILE_VIEW.STEAM
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setSteam(String steam) {
		this.steam = steam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.NNID
	 * @return  the value of USER_PROFILE_VIEW.NNID
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getNnid() {
		return nnid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.NNID
	 * @param nnid  the value for USER_PROFILE_VIEW.NNID
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setNnid(String nnid) {
		this.nnid = nnid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.XBOX_LIVE
	 * @return  the value of USER_PROFILE_VIEW.XBOX_LIVE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getXboxLive() {
		return xboxLive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.XBOX_LIVE
	 * @param xboxLive  the value for USER_PROFILE_VIEW.XBOX_LIVE
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setXboxLive(String xboxLive) {
		this.xboxLive = xboxLive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_PROFILE_VIEW.PSN
	 * @return  the value of USER_PROFILE_VIEW.PSN
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public String getPsn() {
		return psn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_PROFILE_VIEW.PSN
	 * @param psn  the value for USER_PROFILE_VIEW.PSN
	 * @mbggenerated  Wed Feb 01 23:02:13 EST 2017
	 */
	public void setPsn(String psn) {
		this.psn = psn;
	}
}