package com.zfgc.dbobj;

public class UserContactSettingsDbObj {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_CONTACT_SETTINGS.USER_CONTACT_SETTINGS_ID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	private Integer userContactSettingsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_CONTACT_SETTINGS.EMAIL_ADDRESS_ID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	private Integer emailAddressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_CONTACT_SETTINGS.USERS_ID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	private Integer usersId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_CONTACT_SETTINGS.GTALK
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	private String gtalk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_CONTACT_SETTINGS.SKYPE
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	private String skype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_CONTACT_SETTINGS.STEAM
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	private String steam;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_CONTACT_SETTINGS.PSN
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	private String psn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_CONTACT_SETTINGS.NNID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	private String nnid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_CONTACT_SETTINGS.XBOX_LIVE
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	private String xboxLive;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_CONTACT_SETTINGS.USER_CONTACT_SETTINGS_ID
	 * @return  the value of USER_CONTACT_SETTINGS.USER_CONTACT_SETTINGS_ID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public Integer getUserContactSettingsId() {
		return userContactSettingsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_CONTACT_SETTINGS.USER_CONTACT_SETTINGS_ID
	 * @param userContactSettingsId  the value for USER_CONTACT_SETTINGS.USER_CONTACT_SETTINGS_ID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public void setUserContactSettingsId(Integer userContactSettingsId) {
		this.userContactSettingsId = userContactSettingsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_CONTACT_SETTINGS.EMAIL_ADDRESS_ID
	 * @return  the value of USER_CONTACT_SETTINGS.EMAIL_ADDRESS_ID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public Integer getEmailAddressId() {
		return emailAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_CONTACT_SETTINGS.EMAIL_ADDRESS_ID
	 * @param emailAddressId  the value for USER_CONTACT_SETTINGS.EMAIL_ADDRESS_ID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public void setEmailAddressId(Integer emailAddressId) {
		this.emailAddressId = emailAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_CONTACT_SETTINGS.USERS_ID
	 * @return  the value of USER_CONTACT_SETTINGS.USERS_ID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public Integer getUsersId() {
		return usersId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_CONTACT_SETTINGS.USERS_ID
	 * @param usersId  the value for USER_CONTACT_SETTINGS.USERS_ID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public void setUsersId(Integer usersId) {
		this.usersId = usersId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_CONTACT_SETTINGS.GTALK
	 * @return  the value of USER_CONTACT_SETTINGS.GTALK
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public String getGtalk() {
		return gtalk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_CONTACT_SETTINGS.GTALK
	 * @param gtalk  the value for USER_CONTACT_SETTINGS.GTALK
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public void setGtalk(String gtalk) {
		this.gtalk = gtalk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_CONTACT_SETTINGS.SKYPE
	 * @return  the value of USER_CONTACT_SETTINGS.SKYPE
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public String getSkype() {
		return skype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_CONTACT_SETTINGS.SKYPE
	 * @param skype  the value for USER_CONTACT_SETTINGS.SKYPE
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public void setSkype(String skype) {
		this.skype = skype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_CONTACT_SETTINGS.STEAM
	 * @return  the value of USER_CONTACT_SETTINGS.STEAM
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public String getSteam() {
		return steam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_CONTACT_SETTINGS.STEAM
	 * @param steam  the value for USER_CONTACT_SETTINGS.STEAM
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public void setSteam(String steam) {
		this.steam = steam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_CONTACT_SETTINGS.PSN
	 * @return  the value of USER_CONTACT_SETTINGS.PSN
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public String getPsn() {
		return psn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_CONTACT_SETTINGS.PSN
	 * @param psn  the value for USER_CONTACT_SETTINGS.PSN
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public void setPsn(String psn) {
		this.psn = psn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_CONTACT_SETTINGS.NNID
	 * @return  the value of USER_CONTACT_SETTINGS.NNID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public String getNnid() {
		return nnid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_CONTACT_SETTINGS.NNID
	 * @param nnid  the value for USER_CONTACT_SETTINGS.NNID
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public void setNnid(String nnid) {
		this.nnid = nnid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_CONTACT_SETTINGS.XBOX_LIVE
	 * @return  the value of USER_CONTACT_SETTINGS.XBOX_LIVE
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public String getXboxLive() {
		return xboxLive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_CONTACT_SETTINGS.XBOX_LIVE
	 * @param xboxLive  the value for USER_CONTACT_SETTINGS.XBOX_LIVE
	 * @mbg.generated  Sat Nov 17 21:12:54 EST 2018
	 */
	public void setXboxLive(String xboxLive) {
		this.xboxLive = xboxLive;
	}
}